In [2]:
import bibtexparser

In [3]:
import pandas as pd

In [4]:
with open('xai_papers.bib') as bibtex_file:
    bib_database = bibtexparser.load(bibtex_file)

In [5]:
bib_database.entries[1]

{'year': '2022',
 'title': '{Explaining Black Box with Visual Exploration of Latent Space}',
 'publisher': 'The Eurographics Association',
 'isbn': '978-3-03868-184-7',
 'html': 'https://diglib.eg.org/items/a0d08902-8ab1-4720-aabf-e19e4b707159',
 'editor': 'Agus, Marco and Aigner, Wolfgang and Hoellt, Thomas',
 'doi': '10.2312/evs.20221098',
 'booktitle': 'EuroVis 2022 - Short Papers',
 'bibtex_show': 'true',
 'author': 'Bodria, Francesco and Rinzivillo, Salvatore and Fadda, Daniele and Guidotti, Riccardo and Giannotti, Fosca and Pedreschi, Dino',
 'abstract': 'Autoencoders are a powerful yet opaque feature reduction technique, on top of which we propose a novel way for the joint visual exploration of both latent and real space. By interactively exploiting the mapping between latent and real features, it is possible to unveil the meaning of latent features while providing deeper insight into the original variables. To achieve this goal, we exploit and re-adapt existing approaches from eXplainable Artificial Intelligence (XAI) to understand the relationships between the input and latent features. The uncovered relationships between input features and latent ones allow the user to understand the data structure concerning external variables such as the predictions of a classification model. We developed an interactive framework that visually explores the latent space and allows the user to understand the relationships of the input features with model prediction.',
 'ENTRYTYPE': 'inproceedings',
 'ID': '10.2312:evs.20221098'}

In [6]:
for entry in bib_database.entries:
    entry['bibtex_show'] = 'true'

In [7]:
with open('xai_papers.bib', 'w') as bibtex_file:
    bibtexparser.dump(bib_database, bibtex_file)

In [8]:
# change url to html key
for entry in bib_database.entries:
    if 'url' in entry:
        entry['html'] = entry['url']
        del entry['url']

In [9]:
with open('xai_papers.bib', 'w') as bibtex_file:
    bibtexparser.dump(bib_database, bibtex_file)

In [10]:
for entry in bib_database.entries:
    if entry['line'] == 1:
        entry['line'] = '1'

KeyError: 'line'

In [11]:
bib_database.entries[1]

{'year': '2022',
 'title': '{Explaining Black Box with Visual Exploration of Latent Space}',
 'publisher': 'The Eurographics Association',
 'isbn': '978-3-03868-184-7',
 'html': 'https://diglib.eg.org/items/a0d08902-8ab1-4720-aabf-e19e4b707159',
 'editor': 'Agus, Marco and Aigner, Wolfgang and Hoellt, Thomas',
 'doi': '10.2312/evs.20221098',
 'booktitle': 'EuroVis 2022 - Short Papers',
 'bibtex_show': 'true',
 'author': 'Bodria, Francesco and Rinzivillo, Salvatore and Fadda, Daniele and Guidotti, Riccardo and Giannotti, Fosca and Pedreschi, Dino',
 'abstract': 'Autoencoders are a powerful yet opaque feature reduction technique, on top of which we propose a novel way for the joint visual exploration of both latent and real space. By interactively exploiting the mapping between latent and real features, it is possible to unveil the meaning of latent features while providing deeper insight into the original variables. To achieve this goal, we exploit and re-adapt existing approaches from eXplainable Artificial Intelligence (XAI) to understand the relationships between the input and latent features. The uncovered relationships between input features and latent ones allow the user to understand the data structure concerning external variables such as the predictions of a classification model. We developed an interactive framework that visually explores the latent space and allows the user to understand the relationships of the input features with model prediction.',
 'ENTRYTYPE': 'inproceedings',
 'ID': '10.2312:evs.20221098'}

In [12]:
# sort by year, month, author. Consider if some entries have no month or author
for entry in bib_database.entries:
    if 'author' not in entry:
        entry['author'] = '0'
bib_database.entries = sorted(bib_database.entries, key=lambda x: (int(x['year']), x['author']))
# remove month and author only added for sorting (entry['month'] == '0' and entry['author'] == '0')
for entry in bib_database.entries:
    if entry['author'] == '0':
        del entry['author']

In [13]:
bib_database.entries

[{'year': '2018',
  'volume': '51',
  'title': 'A Survey of Methods for Explaining Black Box Models',
  'selected': 'true',
  'publisher': 'Association for Computing Machinery (ACM)',
  'pages': '1–42',
  'number': '5',
  'month': 'August',
  'line': '1',
  'journal': 'ACM Computing Surveys',
  'issn': '1557-7341',
  'html': 'http://dx.doi.org/10.1145/3236009',
  'doi': '10.1145/3236009',
  'bibtex_show': 'true',
  'author': 'Guidotti, Riccardo and Monreale, Anna and Ruggieri, Salvatore and Turini, Franco and Giannotti, Fosca and Pedreschi, Dino',
  'abstract': 'In recent years, many accurate decision support systems have been constructed as black boxes, that is as systems that hide their internal logic to the user. This lack of explanation constitutes both a practical and an ethical issue. The literature reports many approaches aimed at overcoming this crucial weakness, sometimes at the cost of sacrificing accuracy for interpretability. The applications in which black box decision systems can be used are various, and each approach is typically developed to provide a solution for a specific problem and, as a consequence, it explicitly or implicitly delineates its own definition of interpretability and explanation. The aim of this article is to provide a classification of the main problems addressed in the literature with respect to the notion of explanation and the type of black box system. Given a problem definition, a black box type, and a desired explanation, this survey should help the researcher to find the proposals more useful for his own work. The proposed classification of approaches to open black box models should also be useful for putting the many research open questions in perspective.',
  'ENTRYTYPE': 'article',
  'ID': 'Guidotti_2018'},
 {'year': '2019',
  'title': 'Investigating Neighborhood Generation Methods for Explanations of Obscure Image Classifiers',
  'publisher': 'Springer International Publishing',
  'pages': '55–68',
  'month': '0',
  'line': '1',
  'issn': '1611-3349',
  'isbn': '9783030161484',
  'html': 'http://dx.doi.org/10.1007/978-3-030-16148-4_5',
  'doi': '10.1007/978-3-030-16148-4_5',
  'booktitle': 'Lecture Notes in Computer Science',
  'bibtex_show': 'true',
  'author': 'Guidotti, Riccardo and Monreale, Anna and Cariaggi, Leonardo',
  'abstract': 'Given the wide use of machine learning approaches based on opaque prediction models, understanding the reasons behind decisions of black box decision systems is nowadays a crucial topic. We address the problem of providing meaningful explanations in the widely-applied image classification tasks. In particular, we explore the impact of changing the neighborhood generation function for a local interpretable model-agnostic explanator by proposing four different variants. All the proposed methods are based on a grid-based segmentation of the images, but each of them proposes a different strategy for generating the neighborhood of the image for which an explanation is required. A deep experimentation shows both improvements and weakness of each proposed approach.',
  'ENTRYTYPE': 'inbook',
  'ID': 'Guidotti_2019Investigating'},
 {'year': '2019',
  'volume': '34',
  'title': 'Factual and Counterfactual Explanations for Black Box Decision Making',
  'selected': 'true',
  'publisher': 'Institute of Electrical and Electronics Engineers (IEEE)',
  'pages': '14–23',
  'number': '6',
  'month': 'November',
  'line': '1',
  'journal': 'IEEE Intelligent Systems',
  'issn': '1941-1294',
  'html': 'http://dx.doi.org/10.1109/MIS.2019.2957223',
  'doi': '10.1109/mis.2019.2957223',
  'bibtex_show': 'true',
  'author': 'Guidotti, Riccardo and Monreale, Anna and Giannotti, Fosca and Pedreschi, Dino and Ruggieri, Salvatore and Turini, Franco',
  'abstract': 'The rise of sophisticated machine learning models has brought accurate but obscure decision systems, which hide their logic, thus undermining transparency, trust, and the adoption of artificial intelligence (AI) in socially sensitive and safety-critical contexts. We introduce a local rule-based explanation method, providing faithful explanations of the decision made by a black box classifier on a specific instance. The proposed method first learns an interpretable, local classifier on a synthetic neighborhood of the instance under investigation, generated by a genetic algorithm. Then, it derives from the interpretable classifier an explanation consisting of a decision rule, explaining the factual reasons of the decision, and a set of counterfactuals, suggesting the changes in the instance features that would lead to a different outcome. Experimental results show that the proposed method outperforms existing approaches in terms of the quality of the explanations and of the accuracy in mimicking the black box.',
  'ENTRYTYPE': 'article',
  'ID': 'Guidotti_2019Factual'},
 {'year': '2019',
  'title': 'Helping Your Docker Images to Spread Based on Explainable Models',
  'publisher': 'Springer International Publishing',
  'pages': '205–221',
  'month': '0',
  'line': '1',
  'issn': '1611-3349',
  'isbn': '9783030109974',
  'html': 'http://dx.doi.org/10.1007/978-3-030-10997-4_13',
  'doi': '10.1007/978-3-030-10997-4_13',
  'booktitle': 'Lecture Notes in Computer Science',
  'bibtex_show': 'true',
  'author': 'Guidotti, Riccardo and Soldani, Jacopo and Neri, Davide and Brogi, Antonio and Pedreschi, Dino',
  'abstract': 'Docker is on the rise in today’s enterprise IT. It permits shipping applications inside portable containers, which run from so-called Docker images. Docker images are distributed in public registries, which also monitor their popularity. The popularity of an image impacts on its actual usage, and hence on the potential revenues for its developers. In this paper, we present a solution based on interpretable decision tree and regression trees for estimating the popularity of a given Docker image, and for understanding how to improve an image to increase its popularity. The results presented in this work can provide valuable insights to Docker developers, helping them in spreading their images.',
  'ENTRYTYPE': 'inbook',
  'ID': 'Guidotti_2019_Helping'},
 {'year': '2019',
  'title': 'Explaining Multi-label Black-Box Classifiers for Health Applications',
  'publisher': 'Springer International Publishing',
  'pages': '97–110',
  'month': 'August',
  'line': '1,4',
  'issn': '1860-9503',
  'isbn': '9783030244095',
  'html': 'http://dx.doi.org/10.1007/978-3-030-24409-5_9',
  'doi': '10.1007/978-3-030-24409-5_9',
  'booktitle': 'Studies in Computational Intelligence',
  'bibtex_show': 'true',
  'author': 'Panigutti, Cecilia and Guidotti, Riccardo and Monreale, Anna and Pedreschi, Dino',
  'abstract': 'Today the state-of-the-art performance in classification is achieved by the so-called “black boxes”, i.e. decision-making systems whose internal logic is obscure. Such models could revolutionize the health-care system, however their deployment in real-world diagnosis decision support systems is subject to several risks and limitations due to the lack of transparency. The typical classification problem in health-care requires a multi-label approach since the possible labels are not mutually exclusive, e.g. diagnoses. We propose MARLENA, a model-agnostic method which explains multi-label black box decisions. MARLENA explains an individual decision in three steps. First, it generates a synthetic neighborhood around the instance to be explained using a strategy suitable for multi-label decisions. It then learns a decision tree on such neighborhood and finally derives from it a decision rule that explains the black box decision. Our experiments show that MARLENA performs well in terms of mimicking the black box behavior while gaining at the same time a notable amount of interpretability through compact decision rules, i.e. rules with limited length.',
  'ENTRYTYPE': 'inbook',
  'ID': 'Panigutti_2019'},
 {'year': '2019',
  'volume': '33',
  'title': 'Meaningful Explanations of Black Box AI Decision Systems',
  'publisher': 'Association for the Advancement of Artificial Intelligence (AAAI)',
  'pages': '9780–9784',
  'number': '01',
  'month': 'July',
  'line': '1',
  'journal': 'Proceedings of the AAAI Conference on Artificial Intelligence',
  'issn': '2159-5399',
  'html': 'http://dx.doi.org/10.1609/aaai.v33i01.33019780',
  'doi': '10.1609/aaai.v33i01.33019780',
  'bibtex_show': 'true',
  'author': 'Pedreschi, Dino and Giannotti, Fosca and Guidotti, Riccardo and Monreale, Anna and Ruggieri, Salvatore and Turini, Franco',
  'abstract': 'Black box AI systems for automated decision making, often based on machine learning over (big) data, map a user’s features into a class or a score without exposing the reasons why. This is problematic not only for lack of transparency, but also for possible biases inherited by the algorithms from human prejudices and collection artifacts hidden in the training data, which may lead to unfair or wrong decisions. We focus on the urgent open challenge of how to construct meaningful explanations of opaque AI/ML systems, introducing the local-toglobal framework for black box explanation, articulated along three lines: (i) the language for expressing explanations in terms of logic rules, with statistical and causal interpretation; (ii) the inference of local explanations for revealing the decision rationale for a specific case, by auditing the black box in the vicinity of the target instance; (iii), the bottom-up generalization of many local explanations into simple global ones, with algorithms that optimize for quality and comprehensibility. We argue that the local-first approach opens the door to a wide variety of alternative solutions along different dimensions: a variety of data sources (relational, text, images, etc.), a variety of learning problems (multi-label classification, regression, scoring, ranking), a variety of languages for expressing meaningful explanations, a variety of means to audit a black box.',
  'ENTRYTYPE': 'article',
  'ID': 'Pedreschi_2019'},
 {'year': '2020',
  'title': 'Data-Agnostic Local Neighborhood Generation',
  'selected': 'true',
  'publisher': 'IEEE',
  'month': 'November',
  'line': '1,5',
  'html': 'http://dx.doi.org/10.1109/ICDM50108.2020.00122',
  'doi': '10.1109/icdm50108.2020.00122',
  'booktitle': '2020 IEEE International Conference on Data Mining (ICDM)',
  'bibtex_show': 'true',
  'author': 'Guidotti, Riccardo and Monreale, Anna',
  'additional_info': '. *More Information* can be [found here](https://github.com/alshedivat/al-folio/)',
  'abstract': 'Synthetic data generation has been widely adopted in software testing, data privacy, imbalanced learning, machine learning explanation, etc. In such contexts, it is important to generate data samples located within “local” areas surrounding specific instances. Local synthetic data can help the learning phase of predictive models, and it is fundamental for methods explaining the local behavior of obscure classifiers. The contribution of this paper is twofold. First, we introduce a method based on generative operators allowing the synthetic neighborhood generation by applying specific perturbations on a given input instance. The key factor consists in performing a data transformation that makes applicable to any type of data, i.e., data-agnostic. Second, we design a framework for evaluating the goodness of local synthetic neighborhoods exploiting both supervised and unsupervised methodologies. A deep experimentation shows the effectiveness of the proposed method.',
  'ENTRYTYPE': 'inproceedings',
  'ID': 'Guidotti_2020_Data-Agnostic'},
 {'year': '2020',
  'title': 'Black Box Explanation by Learning Image Exemplars in the Latent Feature Space',
  'publisher': 'Springer International Publishing',
  'pages': '189–205',
  'month': '0',
  'line': '1',
  'issn': '1611-3349',
  'isbn': '9783030461508',
  'html': 'http://dx.doi.org/10.1007/978-3-030-46150-8_12',
  'doi': '10.1007/978-3-030-46150-8_12',
  'booktitle': 'Lecture Notes in Computer Science',
  'bibtex_show': 'true',
  'author': 'Guidotti, Riccardo and Monreale, Anna and Matwin, Stan and Pedreschi, Dino',
  'abstract': 'We present an approach to explain the decisions of black box models for image classification. While using the black box to label images, our explanation method exploits the latent feature space learned through an adversarial autoencoder. The proposed method first generates exemplar images in the latent feature space and learns a decision tree classifier. Then, it selects and decodes exemplars respecting local decision rules. Finally, it visualizes them in a manner that shows to the user how the exemplars can be modified to either stay within their class, or to become counter-factuals by “morphing” into another class. Since we focus on black box decision systems for image classification, the explanation obtained from the exemplars also provides a saliency map highlighting the areas of the image that contribute to its classification, and areas of the image that push it into another class. We present the results of an experimental evaluation on three datasets and two black box models. Besides providing the most useful and interpretable explanations, we show that the proposed method outperforms existing explainers in terms of fidelity, relevance, coherence, and stability.',
  'ENTRYTYPE': 'inbook',
  'ID': 'Guidotti_2020_Black_Box'},
 {'year': '2020',
  'volume': '34',
  'title': 'Explaining Image Classifiers Generating Exemplars and Counter-Exemplars from Latent Representations',
  'publisher': 'Association for the Advancement of Artificial Intelligence (AAAI)',
  'pages': '13665–13668',
  'number': '09',
  'month': 'April',
  'line': '1',
  'journal': 'Proceedings of the AAAI Conference on Artificial Intelligence',
  'issn': '2159-5399',
  'html': 'http://dx.doi.org/10.1609/aaai.v34i09.7116',
  'doi': '10.1609/aaai.v34i09.7116',
  'bibtex_show': 'true',
  'author': 'Guidotti, Riccardo and Monreale, Anna and Matwin, Stan and Pedreschi, Dino',
  'abstract': 'We present an approach to explain the decisions of black box image classifiers through synthetic exemplar and counter-exemplar learnt in the latent feature space. Our explanation method exploits the latent representations learned through an adversarial autoencoder for generating a synthetic neighborhood of the image for which an explanation is required. A decision tree is trained on a set of images represented in the latent space, and its decision rules are used to generate exemplar images showing how the original image can be modified to stay within its class. Counterfactual rules are used to generate counter-exemplars showing how the original image can “morph” into another class. The explanation also comprehends a saliency map highlighting the areas that contribute to its classification, and areas that push it into another class. A wide and deep experimental evaluation proves that the proposed method outperforms existing explainers in terms of fidelity, relevance, coherence, and stability, besides providing the most useful and interpretable explanations.',
  'ENTRYTYPE': 'article',
  'ID': 'Guidotti_2020_Image_Classifiers'},
 {'year': '2020',
  'title': 'Explaining Any Time Series Classifier',
  'publisher': 'IEEE',
  'month': 'October',
  'line': '1',
  'html': 'http://dx.doi.org/10.1109/CogMI50398.2020.00029',
  'doi': '10.1109/cogmi50398.2020.00029',
  'booktitle': '2020 IEEE Second International Conference on Cognitive Machine Intelligence (CogMI)',
  'bibtex_show': 'true',
  'author': 'Guidotti, Riccardo and Monreale, Anna and Spinnato, Francesco and Pedreschi, Dino and Giannotti, Fosca',
  'abstract': 'We present a method to explain the decisions of black box models for time series classification. The explanation consists of factual and counterfactual shapelet-based rules revealing the reasons for the classification, and of a set of exemplars and counter-exemplars highlighting similarities and differences with the time series under analysis. The proposed method first generates exemplar and counter-exemplar time series in the latent feature space and learns a local latent decision tree classifier. Then, it selects and decodes those respecting the decision rules explaining the decision. Finally, it learns on them a shapelet-tree that reveals the parts of the time series that must, and must not, be contained for getting the returned outcome from the black box. A wide experimentation shows that the proposed method provides faithful, meaningful and interpretable explanations.',
  'ENTRYTYPE': 'inproceedings',
  'ID': 'Guidotti_2020'},
 {'year': '2020',
  'title': 'Explaining Sentiment Classification with Synthetic Exemplars and Counter-Exemplars',
  'publisher': 'Springer International Publishing',
  'pages': '357–373',
  'month': '0',
  'line': '1',
  'issn': '1611-3349',
  'isbn': '9783030615277',
  'html': 'http://dx.doi.org/10.1007/978-3-030-61527-7_24',
  'doi': '10.1007/978-3-030-61527-7_24',
  'booktitle': 'Lecture Notes in Computer Science',
  'bibtex_show': 'true',
  'author': 'Lampridis, Orestis and Guidotti, Riccardo and Ruggieri, Salvatore',
  'abstract': 'We present xspells, a model-agnostic local approach for explaining the decisions of a black box model for sentiment classification of short texts. The explanations provided consist of a set of exemplar sentences and a set of counter-exemplar sentences. The former are examples classified by the black box with the same label as the text to explain. The latter are examples classified with a different label (a form of counter-factuals). Both are close in meaning to the text to explain, and both are meaningful sentences – albeit they are synthetically generated. xspells generates neighbors of the text to explain in a latent space using Variational Autoencoders for encoding text and decoding latent instances. A decision tree is learned from randomly generated neighbors, and used to drive the selection of the exemplars and counter-exemplars. We report experiments on two datasets showing that xspells outperforms the well-known lime method in terms of quality of explanations, fidelity, and usefulness, and that is comparable to it in terms of stability.',
  'ENTRYTYPE': 'inbook',
  'ID': 'Lampridis_2020'},
 {'year': '2020',
  'title': 'Predicting and Explaining Privacy Risk Exposure in Mobility Data',
  'publisher': 'Springer International Publishing',
  'pages': '403–418',
  'month': '0',
  'line': '5',
  'issn': '1611-3349',
  'isbn': '9783030615277',
  'html': 'http://dx.doi.org/10.1007/978-3-030-61527-7_27',
  'doi': '10.1007/978-3-030-61527-7_27',
  'booktitle': 'Lecture Notes in Computer Science',
  'bibtex_show': 'true',
  'author': 'Naretto, Francesca and Pellungrini, Roberto and Monreale, Anna and Nardini, Franco Maria and Musolesi, Mirco',

In [14]:
#convert to pandas dataframe import bibtexparser
df = pd.DataFrame(bib_database.entries)
df

,year,volume,title,selected,publisher,pages,number,month,line,journal,...,archiveprefix,keywords,copyright,numpages,issue_date,articleno,address,pdf,pubmedid,article-number
0,2018,51,A Survey of Methods for Explaining Black Box M...,true,Association for Computing Machinery (ACM),1–42,5,August,1,ACM Computing Surveys,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019,NaN,Investigating Neighborhood Generation Methods ...,NaN,Springer International Publishing,55–68,NaN,0,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019,34,Factual and Counterfactual Explanations for Bl...,true,Institute of Electrical and Electronics Engine...,14–23,6,November,1,IEEE Intelligent Systems,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019,NaN,Helping Your Docker Images to Spread Based on ...,NaN,Springer International Publishing,205–221,NaN,0,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019,NaN,Explaining Multi-label Black-Box Classifiers f...,NaN,Springer International Publishing,97–110,NaN,August,"1,4",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,2024,abs/2402.17389,FairBelief - Assessing Harmful Beliefs in Lang...,NaN,NaN,NaN,NaN,0,"2,5",CoRR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,2024,14,Advancing Dermatological Diagnostics: Interpre...,NaN,NaN,NaN,7,0,"3,4",Diagnostics,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38611666,753
68,2024,11,Towards Transparent Healthcare: Advancing Loca...,NaN,MDPI,369,4,0,"1,4",Bioengineering,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,2024,NaN,An Overview of Recent Approaches to Enable Div...,NaN,ELRA and ICCL,49--55,NaN,May,"1,2",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"Torino, Italia",NaN,NaN,NaN
70,2024,NaN,Generative Model for Decision Trees,NaN,{AAAI} Press,21116--21124,NaN,0,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
with open('fair_spoke1.bib') as bibtex_file:
    fair_database = bibtexparser.load(bibtex_file)

In [16]:
fair_database.entries[1]

{'keywords': '⛔ No INSPIRE recid found, fair:spoke:1, fair:report:1, status:published, fair:wp:6.1',
 'year': '2023',
 'author': 'Dadà, Silvia and Fabris, Adriano and Neri, Veronica',
 'publisher': 'Orthotes',
 'urldate': '2023-10-04',
 'language': 'it-IT',
 'abstract': 'Etica, conoscenza, spazio pubblico: Il volume tratta dell’apparente divaricazione tra etica e conoscenza scientifica, prassi e teoria...',
 'url': 'https://www.orthotes.com/etica-conoscenza-spazio-pubblico/',
 'isbn': '978-88-9314-373-8',
 'title': 'Etica, conoscenza, spazio pubblico',
 'address': 'Napoli-Salerno',
 'ENTRYTYPE': 'book',
 'ID': 'dada_etica_2023'}

In [17]:
#convert to pandas dataframe import bibtexparser
fair_df = pd.DataFrame(fair_database.entries)
fair_df

,keywords,year,month,author,journal,title,ENTRYTYPE,ID,publisher,urldate,...,issn,shorttitle,pages,booktitle,copyright,volume,series,number,editor,edition
0,"⛔ No INSPIRE recid found, fair:spoke:1, fair:p...",2023,June,"Lanciano, Giacomo and Galli, Filippo and Cucin...",Elsevier Big Data Mining and Analytics,Extending {OpenStack} {Monasca} for {Predictiv...,article,lanciano_extending_2023,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"⛔ No INSPIRE recid found, fair:spoke:1, fair:r...",2023,NaN,"Dadà, Silvia and Fabris, Adriano and Neri, Ver...",NaN,"Etica, conoscenza, spazio pubblico",book,dada_etica_2023,Orthotes,2023-10-04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"fair:spoke:1, status:accepted, fair:report:1, ...",2023,October,"Naretto, Francesca and Pellungrini, Roberto an...",NaN,{EXPHLOT}: {EXplainable} {Privacy} assessment ...,inproceedings,naretto_exphlot_2023,Springer,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"⛔ No INSPIRE recid found, fair:spoke:1, fair:r...",2023,NaN,"Puccietti, Giovanni and Rodgers, A and Alzetta...",NaN,{AI}-generated {News} {May} {Be} {Coming} in {...,inproceedings,puccietti_ai-generated_2023,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2023,NaN,"Manca, Danilo",NaN,La mediazione tecnica nel conflitto fra le due...,book,manca_mediazione_2023,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2024,October,"Tortorella, Domenico and Micheli, Alessio",NaN,Continual {Learning} with {Graph} {Reservoirs}...,inproceedings,tortorella_continual_2024,Ciaco - i6doc.com,NaN,...,NaN,NaN,35--40,{ESANN} 2024 proceedings,NaN,NaN,NaN,NaN,NaN,NaN
311,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2024,September,"Tortorella, Domenico and Micheli, Alessio",NaN,Onion {Echo} {State} {Networks}: {A} {Prelimin...,inproceedings,tortorella_onion_2024,"Springer, Cham",NaN,...,NaN,NaN,117--128,Artificial {Neural} {Networks} and {Machine} {...,NaN,15025,Lecture {Notes} in {Computer} {Science},NaN,NaN,NaN
312,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2024,September,"Ceni, Andrea and Dominey, Peter Ford and Galli...",NaN,Continuously {Deep} {Recurrent} {Neural} {Netw...,inproceedings,ceni_continuously_2024,"Springer, Cham",NaN,...,NaN,NaN,59--73,Machine {Learning} and {Knowledge} {Discovery}...,NaN,14947,Lecture {Notes} in {Computer} {Science},NaN,NaN,NaN
313,"⛔ No INSPIRE recid found, fair:spoke:1, fair:r...",2023,NaN,"Dadà, Silvia",NaN,Principi comuni e valori condivisi nei codici ...,incollection,dada_principi_2023-1,Orthotes,NaN,...,NaN,NaN,NaN,Etiche applicate e nuovi soggetti morali,NaN,NaN,NaN,NaN,NaN,NaN
314,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2024,NaN,"Micheli, Alessio and Tortorella, Domenico",Neurocomputing,Designs of {Graph} {Echo} {State} {Networks} f...,article,micheli_designs_2024,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,597,NaN,NaN,NaN,NaN

In [18]:
fair_df.columns

Index(['keywords', 'year', 'month', 'author', 'journal', 'title', 'ENTRYTYPE',
       'ID', 'publisher', 'urldate', 'language', 'abstract', 'url', 'isbn',
       'address', 'note', 'doi', 'issn', 'shorttitle', 'pages', 'booktitle',
       'copyright', 'volume', 'series', 'number', 'editor', 'edition'],
      dtype='object')

In [19]:
# filter doi_fair by doi where doi is not the same as in df and date is >=2023
doi_fair = fair_df[~fair_df['doi'].isin(df['doi'])]

In [20]:
doi_fair = doi_fair[doi_fair['year'] >= '2023']

In [21]:
doi_fair

,keywords,year,month,author,journal,title,ENTRYTYPE,ID,publisher,urldate,...,issn,shorttitle,pages,booktitle,copyright,volume,series,number,editor,edition
26,"fair:spoke:1, fair:report:0, status:published,...",2023,April,"Trotta, Angelo and Ziosi, Marta and Lomonaco, ...",AI \& SOCIETY,The future of ethics in {AI}: challenges and o...,article,trotta_future_2023,NaN,2023-07-25,...,1435-5655,The future of ethics in {AI},439--441,NaN,NaN,38,NaN,2,NaN,NaN
30,"fair:spoke:1, fair:report:0, status:published,...",2023,January,"Cococcioni, Marco and Fiorini, Francesco and P...",Mathematics,Modelling {Heavy} {Tailed} {Phenomena} {Using}...,article,cococcioni_modelling_2023,NaN,2023-07-25,...,2227-7390,NaN,1758,NaN,http://creativecommons.org/licenses/by/3.0/,11,NaN,7,NaN,NaN
33,"fair:spoke:1, fair:report:0, status:unpublishe...",2023,July,"Quarantiello, Luigi and Marzeddu, Simone and G...",NaN,{LuckyMera}: a {Modular} {AI} {Framework} for ...,misc,quarantiello_luckymera_2023,arXiv,2023-07-25,...,NaN,{LuckyMera},NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,"fair:spoke:1, fair:report:0, status:published,...",2023,NaN,"Esuli, Andrea and Fabris, Alessandro and Moreo...",NaN,Learning to {Quantify},book,esuli_learning_2023,Springer International Publishing,2023-07-25,...,NaN,NaN,NaN,NaN,NaN,47,The {Information} {Retrieval} {Series},NaN,NaN,NaN
36,"fair:spoke:1, fair:report:0, status:published,...",2023,NaN,"Turchi, Tommaso and Carta, Silvio and Ambrosin...",NaN,Human-{AI} {Co}-creation: {Evaluating} the {Im...,inproceedings,turchi_human-ai_2023,Springer Nature Switzerland,NaN,...,NaN,Human-{AI} {Co}-creation,35--51,End-{User} {Development},NaN,NaN,Lecture {Notes} in {Computer} {Science},NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
309,"fair:spoke:1, status:published, fair:wp:2.4, f...",2024,NaN,"Triggiano, Francesco and Romito, Marco",IEEE Access,Gaussian processes based data augmentation and...,article,triggiano_gaussian_2024,NaN,2024-03-11,...,2169-3536,NaN,NaN,NaN,NaN,12,NaN,NaN,NaN,NaN
310,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2024,October,"Tortorella, Domenico and Micheli, Alessio",NaN,Continual {Learning} with {Graph} {Reservoirs}...,inproceedings,tortorella_continual_2024,Ciaco - i6doc.com,NaN,...,NaN,NaN,35--40,{ESANN} 2024 proceedings,NaN,NaN,NaN,NaN,NaN,NaN
311,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2024,September,"Tortorella, Domenico and Micheli, Alessio",NaN,Onion {Echo} {State} {Networks}: {A} {Prelimin...,inproceedings,tortorella_onion_2024,"Springer, Cham",NaN,...,NaN,NaN,117--128,Artificial {Neural} {Networks} and {Machine} {...,NaN,15025,Lecture {Notes} in {Computer} {Science},NaN,NaN,NaN
312,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2024,September,"Ceni, Andrea and Dominey, Peter Ford and Galli...",NaN,Continuously {Deep} {Recurrent} {Neural} {Netw...,inproceedings,ceni_continuously_2024,"Springer, Cham",NaN,...,NaN,NaN,59--73,Machine {Learning} and {Knowledge} {Discovery}...,NaN,14947,Lecture {Notes} in {Computer} {Science},NaN,NaN,NaN
314,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2024,NaN,"Micheli, Alessio and Tortorella, Domenico",Neurocomputing,Designs of {Graph} {Echo} {State} {Networks} f...,article,micheli_designs_2024,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,597,NaN,NaN,NaN,NaN

In [22]:
# doi_fair.to_excel('doi_fair.xlsx')

In [23]:
#open links in browser from doi_fair column: 'doi'

In [24]:
names = []
for bib in bib_database.entries:
    if 'author' in bib:
        ats = bib['author'].split(' and ')
        for at in ats:
            c= at.split(', ')[0].strip()
            if c not in names and len(c) < 20 and 'and' not in c:
                names.append(c)
names

['Guidotti',
 'Monreale',
 'Ruggieri',
 'Turini',
 'Giannotti',
 'Pedreschi',
 'Cariaggi',
 'Soldani',
 'Neri',
 'Brogi',
 'Panigutti',
 'Matwin',
 'Spinnato',
 'Lampridis',
 'Naretto',
 'Pellungrini',
 'Nardini',
 'Musolesi',
 'Perotti',
 'Setzu',
 'Bacciu',
 'Lisboa',
 'Vellido',
 'Bonsignori',
 'Chatila',
 'Dignum',
 'Fisher',
 'Morik',
 'Russell',
 'Yeung',
 'D’Onofrio',
 'Manerba',
 'Metta',
 'Yin',
 'Gallinari',
 'Rinzivillo',
 'Bosi',
 'Panisson',
 'Bajardi',
 'Resta',
 'Minervini',
 'Bodria',
 'Fadda',
 'Marchiori Manerba',
 'Nogueira',
 'Pugnana',
 'Gama',
 'Beretta',
 'Nanni',
 'Maccagnola',
 'Paciello',
 'Farina',
 'Theissler',
 'Schlegel',
 'Voukelatou',
 'Miliou',
 'Pappalardo',
 'Cinquini',
 'Mattei',
 'Laura State',
 'Salvatore Ruggieri',
 'Franco Turini',
 'Liguori',
 'Caroprese',
 'Minici',
 'Veloso',
 'Manco',
 'Morini',
 'Massidda',
 'Poggioli',
 'Cappuccio',
 'Lanzilotti',
 'Muscato']

In [25]:
#filter doi_fair by authors. If at last one of the names is in one of the authors of the fair database, keep the entry
selected_fair = doi_fair[doi_fair['author'].str.contains('|'.join(names))]

In [26]:
selected_fair

,keywords,year,month,author,journal,title,ENTRYTYPE,ID,publisher,urldate,...,issn,shorttitle,pages,booktitle,copyright,volume,series,number,editor,edition
43,"fair:spoke:1, fair:report:0, status:submitted,...",2023,June,"Cornacchia, Giuliano and Nanni, Mirco and Papp...",NaN,One-{Shot} {Traffic} {Assignment} with {Forwar...,misc,cornacchia_one-shot_2023,arXiv,2023-07-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,"fair:spoke:1, status:published, fair:wp:4.3, F...",2023,June,"Cornacchia, Giuliano and Nanni, Mirco and Pedr...",NaN,The {Effects} of {Route} {Randomization} on {U...,inproceedings,cornacchia_effects_2023,NaN,2023-07-25,...,NaN,NaN,75--87,{SUMO} {Conference} {Proceedings},"Copyright (c) 2023 Giuliano Cornacchia, Mirco ...",4,NaN,NaN,NaN,NaN
72,"⛔ No INSPIRE recid found, fair:spoke:1, fair:r...",2023,NaN,"State, Laura and Ruggieri, Salvatore and Turin...",NaN,Declarative {Reasoning} on {Explanations} {Usi...,inproceedings,state_declarative_2023,Springer Nature Switzerland,NaN,...,NaN,NaN,132--141,Logics in {Artificial} {Intelligence},NaN,NaN,Lecture {Notes} in {Computer} {Science},NaN,NaN,NaN
74,"fair:spoke:1, fair:report:0, fair:wp:1.5, stat...",2023,NaN,"Beretta, Lorenzo and Nardini, Franco Maria and...",IEEE Transactions on Knowledge and Data Engine...,An {Optimal} {Algorithm} for {Finding} {Champi...,article,beretta_optimal_2023,NaN,NaN,...,1558-2191,NaN,1--13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2024,NaN,"Setzu, Mattia and Corbara, Silvia and Monreale...",Journal on Computing and Cultural Heritage,Explainable {Authorship} {Identification} in {...,article,setzu_explainable_2024,NaN,2024-04-22,...,1556-4673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,"fair:spoke:1, status:published, fair:author:fo...",2023,October,"Rocchietti, Guido and Frieder, Ophir and Munte...",NaN,Commonsense {Injection} in {Conversational} {S...,inproceedings,rocchietti_commonsense_2023,IEEE,2024-02-28,...,NaN,Commonsense {Injection} in {Conversational} {S...,48--55,2023 {IEEE} {International} {Conference} on {W...,NaN,NaN,NaN,NaN,NaN,NaN
80,"fair:spoke:1, status:published, fair:HAI, fair...",2023,October,"Lucchese, Claudio and Minello, Giorgia and Nar...",NaN,Can {Embeddings} {Analysis} {Explain} {Large} ...,inproceedings,lucchese_can_2023,ACM,2024-02-28,...,NaN,NaN,4150--4154,Proceedings of the 32nd {ACM} {International} ...,NaN,NaN,NaN,NaN,NaN,NaN
82,"fair:spoke:1, status:published, fair:author:fo...",2023,October,"Galimzhanova, Elnara and Muntean, Cristina Ioa...",NaN,Rewriting {Conversational} {Utterances} with {...,inproceedings,galimzhanova_rewriting_2023,IEEE,2024-02-28,...,NaN,NaN,56--63,2023 {IEEE} {International} {Conference} on {W...,NaN,NaN,NaN,NaN,NaN,NaN
85,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2023,NaN,"Paparella, Vincenzo and Anelli, Vito Walter an...",NaN,Post-hoc {Selection} of {Pareto}-{Optimal} {So...,article,paparella_post-hoc_2023,NaN,2024-02-28,...,NaN,NaN,NaN,NaN,Creative Commons Attribution 4.0 International,NaN,NaN,NaN,NaN,NaN
96,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2023,NaN,"Corbucci, Luca and Monreale, Anna and Panigutt...",NaN,Semantic {Enrichment} of {Explanations} of {AI...,inproceedings,corbucci_semantic_2023,Springer Nature Switzerland,2024-02-26,...,NaN,NaN,216--229,Discovery {Science},NaN,14276,NaN,NaN,NaN,NaN
110,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2023,December,"Tripto, Nafis and Uchendu, Adaku and Le, Thai ...",NaN,{HANSEN}: {Human} and {AI} {Spoken} {Text} {Be...,inproceedings,tripto_hansen_2023,Association for Computational Linguistics,2024-02-21,...,NaN,{HANSEN},13706--13724,{EMNLP},NaN,NaN,NaN,NaN,"Bouamor, Houda and Pino, Juan and Bali, Kalika",NaN
122,"⛔ No INSPIRE recid found, fair:spoke:1, fair:r...",2023,May,"Ducange, Pietro and Marcelloni, Francesco and ...",NaN,Trustworthy {AI} for {Next} {Generation} {Netw...,inproceedings,ducange_trustworthy_2023,NaN,2023-09-28,...,NaN,Trustworthy {AI} for {Next} {Generation} {Netw...,NaN,NaN,Creative Commons Attribution 4.0 International...,NaN,NaN,NaN,NaN,NaN
134,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2023,December,"Lusito, Salvatore and Pugnana, Andrea and Guid...",Machine Learning,Solving imbalanced learning with outlier detec...,article,lusito_solving_2023,NaN,2024-02-28,...,1573-0565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2023,December,"Landi, Cristiano and Guidotti, Riccardo and Na...",NaN,The {Trajectory} {Interval} {Forest} {Classifi...,inproceedings,landi_trajectory_2023,Association for Computing Machinery,2024-02-28,...,NaN,NaN,1--4,Proceedings of the 31st {ACM} {International} ...,NaN,NaN,{SIGSPATIAL} '23,NaN,NaN,NaN
144,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2023,NaN,"Setzu, Mattia and Ruggieri, Salvatore",NaN,Correlation and {Unintended} {Biases} on {Univ...,inproceedings,setzu_correlation_2023,NaN,2024-02-21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2023,December,"Maslennikova, Aleksandra and Rotelli, Daniela ...",Journal of Learning Analytics,Session-{Based} {Time}-{Window} {Identificatio...,article,maslennikova_session-based_2023,NaN,2024-02-26,...,1929-7750,NaN,7--27,NaN,NaN,10,NaN,3,NaN,NaN
146,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2023,NaN,"Mazzoni, Federico and Manerba, Marta Marchiori...",NaN,{GenFair}: {A} {Genetic} {Fairness}-{Enhancing...,inproceedings,mazzoni_genfair_2023,Springer Nature Switzerland,NaN,...,NaN,{GenFair},356--371,Discovery {Science},NaN,NaN,Lecture {Notes} in {Computer} {Science},NaN,"Bifet, Albert and Lorena, Ana Carolina and Rib...",NaN
147,"⛔ No INSPIRE recid found, status:published, fa...",2023,NaN,"Cinquini, Martina and Giannotti, Fosca and Gui...",NaN,Handling {Missing} {Values} in {Local} {Post}-...,inproceedings,cinquini_handling_2023,Springer Nature Switzerland,NaN,...,NaN,NaN,256--278,Explainable {Artificial} {Intelligence},NaN,NaN,Communications in {Computer} and {Information}...,NaN,"Longo, Luca",NaN
148,"⛔ No INSPIRE recid found, status:published, fa...",2023,NaN,"Guidotti, Riccardo and Landi, Cristiano and Be...",NaN,Interpretable {Data} {Partitioning} {Through} ...,inproceedings,guidotti_interpretable_2023,Springer Nature Switzerland,NaN,...,NaN,NaN,492--507,Discovery {Science},NaN,NaN,Lecture {Notes} in {Computer} {Science},NaN,"Bifet, Albert and Lorena, Ana Carolina and Rib...",NaN
149,"⛔ No INSPIRE recid found, status:published, fa...",2023,NaN,"Corbucci, Luca and Guidotti, Riccardo and Monr...",NaN,Explaining {Black}-{Boxes} in {Federated} {Lea...,inproceedings,corbucci_explaining_2023,Springer Nature Switzerland,NaN,...,NaN,NaN,151--163,Explainable {Artificial} {Intelligence},NaN,NaN,Communications in {Computer} and {Information}...,NaN,"Longo, Luca",NaN
152,"status:published, fair:HAI, fair:wp:1.4, fair:...",2024,NaN,"Serafim De Sousa, Paulo B. and Crescenzi, Pier...",NaN,Exploring {Large} {Language} {Models} {Capabil...,inproceedings,serafim_de_sousa_exploring_2024,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,"status:published, fair:HAI, fair:wp:1.1, fair:...",2024,NaN,"Scopelliti, Milena and Strijdonck, Cato and Ge...",NaN,Pre- and {Post}-{Liver} {Transplant} {Diabetes...,inproceedings,scopelliti_pre-_2024,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,"fair:spoke:1, fair:report:1, fair:wp:1.5, stat...",2023,July,"Punzi, Clara and Maslennikova, Aleksandra and ...",NaN,Explaining {Socio}-demographic and {Behavioral...,inproceedings,punzi_explaining_2023,Springer,NaN,...,NaN,NaN,NaN,Explainable {Artificial} {Intelligence} {First...,NaN,NaN,NaN,NaN,NaN,NaN
160,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2023,November,"Peduzzi, Giulia and Felici, Alessio and Pellun...",Digestive and Liver Disease,Analysis of exposome and genetic variability s...,article,peduzzi_analysis_2023,NaN,2024-03-01,...,15908658,NaN,S1590865823010046,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,"status:accepted, fair:HAI, fair:wp:1.3, fair:R...",2024,NaN,"Lenders, Daphne and Pugnana, Andrea and Pellun...",NaN,Interpretable and {Fair} {Mechanisms} for {Abs...,inproceedings,lenders_interpretable_2024,Springer Nature Switzerland,NaN,...,NaN,NaN,416--433,Machine {Learning} and {Knowledge} {Discovery}...,NaN,14947,NaN,NaN,NaN,NaN
193,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2024,NaN,"Fernandez, Guillermo and Guidotti, Riccardo an...",NaN,{FLocalX} - {Local} to {Global} {Fuzzy} {Expla...,inproceedings,fernandez_flocalx_2024,Springer Nature Switzerland,2024-04-22,...,NaN,NaN,197--209,Intelligent {Data} {Analysis},NaN,14642,NaN,NaN,NaN,NaN
206,"⛔ No INSPIRE recid found, status:submitted, fa...",2024,May,"Palomba, Filippo and Pugnana, Andrea and Alvar...",NaN,A {Causal} {Framework} for {Evaluating} {Defer...,inproceedings,palomba_causal_2024,arXiv,2024-06-12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
213,"⛔ No INSPIRE recid found, fair:report:3",2023,NaN,"Corbucci, Luca and Guidotti, Riccardo and Monr...",NaN,Explaining {Black}-{Boxes} in {Federated} {Lea...,inproceedings,corbucci_explaining_2023-1,Springer Nature Switzerland,NaN,...,NaN,NaN,151--163,Explainable {Artificial} {Intelligence},NaN,NaN,NaN,NaN,"Longo, Luca",NaN
223,"⛔ No INSPIRE recid found, status:published, fa...",2024,NaN,"Nardini, Franco Maria and Rulli, Cosimo and Ve...",NaN,Efficient {Multi}-vector {Dense} {Retrieval} w...,inproceedings,goharian_efficient_2024,Springer Nature Switzerland,2024-06-17,...,NaN,NaN,3--17,Advances in {Information} {Retrieval},NaN,14609,NaN,NaN,"Goharian, Nazli and Tonellotto, Nicola and He,...",NaN
226,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2023,NaN,"Guidotti, Riccardo and Landi, Cristiano and Be...",NaN,Interpretable {Data} {Partitioning} {Through} ...,inproceedings,bifet_interpretable_2023,Springer Nature Switzerland,2024-05-08,...,NaN,NaN,492--507,Discovery {Science},NaN,14276,NaN,NaN,"Bifet, Albert and Lorena, Ana Carolina and Rib...",NaN
227,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2024,NaN,"Mazzoni, Federico and Guidotti, Riccardo and M...",NaN,A {Frank} {System} for {Co}-{Evolutionary} {Hy...,inproceedings,miliou_frank_2024,Springer Nature Switzerland,2024-05-08,...,NaN,NaN,236--248,Advances in {Intelligent} {Data} {Analysis} {X...,NaN,14642,NaN,NaN,"Miliou, Ioanna and Piatkowski, Nico and Papape...",NaN
231,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2023,November,"Landi, Cristiano and Guidotti, Riccardo and Na...",NaN,The {Trajectory} {Interval} {Forest} {Classifi...,inproceedings,landi_trajectory_2023-1,ACM,2024-05-08,...,NaN,NaN,1--4,Proceedings of the 31st {ACM} {International} ...,NaN,NaN,NaN,NaN,NaN,NaN
232,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2024,April,"Fedele, Andrea and Guidotti, Riccardo and Pedr...",Machine Learning,Explaining {Siamese} networks in few-shot lear...,article,fedele_explaining_2024,NaN,2024-05-08,...,"0885-6125, 1573-0565",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
239,"⛔ No INSPIRE recid found, fair:wp:6.2, fair:re...",2024,NaN,"Gomes, Fernanda Oliveira and Pellungrini, Robe...",IEEE Access,{TrajectGuard}: {A} {Comprehensive} {Privacy}-...,article,gomes_trajectguard_2024,NaN,2024-10-08,...,2169-3536,{TrajectGuard},136354--136378,NaN,https://creativecommons.org/licenses/by-nc-nd/...,12,NaN,NaN,NaN,NaN
244,"⛔ No INSPIRE recid found, status:published, fa...",2024,May,"Nardini, Franco Maria and Rulli, Cosimo and Tr...",NaN,Distilled {Neural} {Networks} for {Efficient} ...,inproceedings,nardini_distilled_2024,IEEE,2024-10-25,...,NaN,Distilled {Neural} {Networks} for {Efficient} ...,5693--5694,2024 {IEEE} 40th {International} {Conference} ...,https://doi.org/10.15223/policy-029,NaN,NaN,NaN,NaN,NaN
257,"⛔ No INSPIRE recid found, fair:spoke:1, fair:w...",2024,October,"Busolin, Francesco and Lucchese, Claudio and N...",NaN,Early {Exit} {Strategies} for {Approximate} k ...,inproceedings,busolin_early_2024,ACM,2024-10-25,...,NaN,NaN,3647--3652,Proceedings of the 33rd {ACM} {International} ...,NaN,NaN,NaN,NaN,NaN,NaN
258,"⛔ No INSPIRE recid found, status:published, wp...",2024,October,"Bruch, Sebastian and Nardini, Franco Maria and...",NaN,Pairing {Clustered} {Inverted} {Indexes} with ...,inproceedings,bruch_pairing_2024,ACM,2024-10-25,...,NaN,NaN,3642--3646,Proceedings of the 33rd {ACM} {International} ...,NaN,NaN,NaN,NaN,NaN,NaN
259,"⛔ No INSPIRE recid found, status:published, wp...",2024,July,"Vecchiato, Thomas and Lucchese, Claudio and Na...",NaN,A {Learning}-to-{Rank} {Formulation} of {Clust...,inproceedings,vecchiato_learning--rank_2024,ACM,2024-10-25,...,NaN,NaN,2261--2265,Proceedings of the 47th {International} {ACM} ...,NaN,NaN,NaN,NaN,NaN,NaN
260,"⛔ No INSPIRE recid found, status:published, fa...",2024,July,"Bruch, Sebastian and Nardini, Franco Maria and...",NaN,Efficient {Inverted} {Indexes} for {Approximat...,inproceedings,bruch_efficient_2024,Association for Computing Machinery,2024-10-25,...,NaN,NaN,152--162,Proceedings of the 47th {International} {ACM} ...,NaN,NaN,{SIGIR} '24,NaN,NaN,NaN
261,"⛔ No INSPIRE recid found, status:published, wp...",2024,November,"Bruch, Sebastian and Nardini, Franco Maria and...",ACM Transactions on Information Systems,Bridging {Dense} and {Sparse} {Maximum} {Inner...,article,bruch_bridging_2024,NaN,2024-10-25,...,"1046-8188, 1558-2868",NaN,1--38,NaN,NaN,42,NaN,6,NaN,NaN
267,"⛔ No INSPIRE recid found, status:published, wp...",2024,September,"Nardini, Franco Maria and Trani, Roberto and V...",Discover Computing,Learning bivariate scoring functions for ranking,article,nardini_learning_2024,NaN,2024-10-25,...,2948-2992,NaN,33,NaN,NaN,27,NaN,1,NaN,NaN
289,"⛔ No INSPIRE recid found, fair:report:4",2024,NaN,"Pierotti, Mariarita and Monreale, Anna and De ...",NaN,Artificial {Intelligence} in {Accounting} and ...,book,pierotti_artificial_2024,Springer Nature Switzerland,NaN,...,NaN,Artificial {Intelligence} in {Accounting} and ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1st ed. 2024
300,"fair:spoke:1, fair:report:1, status:published,...",2023,October,"Corcuera Bárcena, José Luis and Ducange, Pietr...",Computer Communications,Enabling federated learning of explainable {AI...,article,corcuera_barcena_enabling_2023,NaN,2023-09-28,...,0140-3664,NaN,356--375,NaN,NaN,210,NaN,NaN,NaN,NaN

In [95]:
import webbrowser
import time
for url in selected_fair['url']:
    try:
        webbrowser.open(url)
        time.sleep(3)
    except:
        print('error for url: ', url)

error for url:  nan
error for url:  nan
error for url:  nan
error for url:  nan
error for url:  nan
error for url:  nan
error for url:  nan
error for url:  nan

In [27]:
xai_selection = pd.read_excel('candidates_for_xai.xlsx')

In [28]:
xai_selected = xai_selection[xai_selection['XAI'] == 'yes']

In [29]:
#join xai_selected with df on doi check if there are any duplicates
xai_selected = xai_selected.rename(columns={'DOI': 'doi'})
xai_selected = xai_selected.drop(columns=['XAI'])

In [38]:
xai_selected

,Unnamed: 0,keywords,year,title,month,author,journal,ENTRYTYPE,ID,publisher,...,issn,shorttitle,pages,booktitle,copyright,volume,series,number,editor,edition
28,44,"fair:spoke:1, status:published, fair:wp:4.3, F...",2023,The {Effects} of {Route} {Randomization} on {U...,June,"Cornacchia, Giuliano and Nanni, Mirco and Pedr...",NaN,inproceedings,cornacchia_effects_2023,NaN,...,NaN,NaN,75--87,{SUMO} {Conference} {Proceedings},"Copyright (c) 2023 Giuliano Cornacchia, Mirco ...",4.0,NaN,NaN,NaN,NaN
29,77,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2024,Explainable {Authorship} {Identification} in {...,NaN,"Setzu, Mattia and Corbara, Silvia and Monreale...",Journal on Computing and Cultural Heritage,article,setzu_explainable_2024,NaN,...,1556-4673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,96,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2023,Semantic {Enrichment} of {Explanations} of {AI...,NaN,"Corbucci, Luca and Monreale, Anna and Panigutt...",NaN,inproceedings,corbucci_semantic_2023,Springer Nature Switzerland,...,NaN,NaN,216--229,Discovery {Science},NaN,14276.0,NaN,NaN,NaN,NaN
31,147,"⛔ No INSPIRE recid found, status:published, fa...",2023,Handling {Missing} {Values} in {Local} {Post}-...,NaN,"Cinquini, Martina and Giannotti, Fosca and Gui...",NaN,inproceedings,cinquini_handling_2023,Springer Nature Switzerland,...,NaN,NaN,256--278,Explainable {Artificial} {Intelligence},NaN,NaN,Communications in {Computer} and {Information}...,NaN,"Longo, Luca",NaN
32,148,"⛔ No INSPIRE recid found, status:published, fa...",2023,Interpretable {Data} {Partitioning} {Through} ...,NaN,"Guidotti, Riccardo and Landi, Cristiano and Be...",NaN,inproceedings,guidotti_interpretable_2023,Springer Nature Switzerland,...,NaN,NaN,492--507,Discovery {Science},NaN,NaN,Lecture {Notes} in {Computer} {Science},NaN,"Bifet, Albert and Lorena, Ana Carolina and Rib...",NaN
33,149,"⛔ No INSPIRE recid found, status:published, fa...",2023,Explaining {Black}-{Boxes} in {Federated} {Lea...,NaN,"Corbucci, Luca and Guidotti, Riccardo and Monr...",NaN,inproceedings,corbucci_explaining_2023,Springer Nature Switzerland,...,NaN,NaN,151--163,Explainable {Artificial} {Intelligence},NaN,NaN,Communications in {Computer} and {Information}...,NaN,"Longo, Luca",NaN
34,152,"status:published, fair:HAI, fair:wp:1.4, fair:...",2024,Exploring {Large} {Language} {Models} {Capabil...,NaN,"Serafim De Sousa, Paulo B. and Crescenzi, Pier...",NaN,inproceedings,serafim_de_sousa_exploring_2024,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,160,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2023,Analysis of exposome and genetic variability s...,November,"Peduzzi, Giulia and Felici, Alessio and Pellun...",Digestive and Liver Disease,article,peduzzi_analysis_2023,NaN,...,15908658,NaN,S1590865823010046,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,191,"status:accepted, fair:HAI, fair:wp:1.3, fair:R...",2024,Interpretable and {Fair} {Mechanisms} for {Abs...,NaN,"Lenders, Daphne and Pugnana, Andrea and Pellun...",NaN,inproceedings,lenders_interpretable_2024,Springer Nature Switzerland,...,NaN,NaN,416--433,Machine {Learning} and {Knowledge} {Discovery}...,NaN,14947.0,NaN,NaN,NaN,NaN
37,193,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2024,{FLocalX} - {Local} to {Global} {Fuzzy} {Expla...,NaN,"Fernandez, Guillermo and Guidotti, Riccardo an...",NaN,inproceedings,fernandez_flocalx_2024,Springer Nature Switzerland,...,NaN,NaN,197--209,Intelligent {Data} {Analysis},NaN,14642.0,NaN,NaN,NaN,NaN
38,213,"⛔ No INSPIRE recid found, fair:report:3",2023,Explaining {Black}-{Boxes} in {Federated} {Lea...,NaN,"Corbucci, Luca and Guidotti, Riccardo and Monr...",NaN,inproceedings,corbucci_explaining_2023-1,Springer Nature Switzerland,...,NaN,NaN,151--163,Explainable {Artificial} {Intelligence},NaN,NaN,NaN,NaN,"Longo, Luca",NaN
39,226,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2023,Interpretable {Data} {Partitioning} {Through} ...,NaN,"Guidotti, Riccardo and Landi, Cristiano and Be...",NaN,inproceedings,bifet_interpretable_2023,Springer Nature Switzerland,...,NaN,NaN,492--507,Discovery {Science},NaN,14276.0,NaN,NaN,"Bifet, Albert and Lorena, Ana Carolina and Rib...",NaN
40,227,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2024,A {Frank} {System} for {Co}-{Evolutionary} {Hy...,NaN,"Mazzoni, Federico and Guidotti, Riccardo and M...",NaN,inproceedings,miliou_frank_2024,Springer Nature Switzerland,...,NaN,NaN,236--248,Advances in {Intelligent} {Data} {Analysis} {X...,NaN,14642.0,NaN,NaN,"Miliou, Ioanna and Piatkowski, Nico and Papape...",NaN
41,232,"⛔ No INSPIRE recid found, fair:spoke:1, status...",2024,Explaining {Siamese} networks in few-shot lear...,April,"Fedele, Andrea and Guidotti, Riccardo and Pedr...",Machine Learning,article,fedele_explaining_2024,NaN,...,"0885-6125, 1573-0565",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
xai_selected['doi'].to_list()

['10.52825/scp.v4i.217',
 '10.1145/3654675',
 '10.1007/978-3-031-45275-8_15',
 '10.1007/978-3-031-44067-0_14',
 '10.1007/978-3-031-45275-8_33',
 '10.1007/978-3-031-44067-0_8',
 '10.3233/FAIA240183',
 '10.1016/j.dld.2023.10.015',
 '10.1007/978-3-031-70368-3_25',
 '10.1007/978-3-031-58553-1_16',
 '10.1007/978-3-031-44067-0_8',
 '10.1007/978-3-031-45275-8_33',
 '10.1007/978-3-031-58553-1_19',
 '10.1007/s10994-024-06529-8']

In [42]:
import requests

def get_bibtex_from_doi(doi):
    """
    Retrieve BibTeX citation for a given DOI
    
    Args:
        doi (str): The DOI to look up
        
    Returns:
        str: BibTeX citation or error message
    """
    # Base URL for DOI resolution
    url = f'https://doi.org/{doi}'
    
    # Headers to request BibTeX format
    headers = {
        'Accept': 'application/x-bibtex',
        'User-Agent': 'Mozilla/5.0' # Some servers require a user agent
    }
    
    try:
        # Make the request
        response = requests.get(url, headers=headers)
        
        # Check if request was successful
        if response.status_code == 200:
            return response.text
        else:
            return f"Error: Unable to retrieve citation (Status code: {response.status_code})"
            
    except requests.exceptions.RequestException as e:
        return f"Error: {str(e)}"


# Example DOI
doi = "10.1038/s41586-021-03819-2"  # Replace with your DOI

bibtex = get_bibtex_from_doi(doi)

In [45]:
dois_list = xai_selected['doi'].to_list()

In [48]:
#get bibtex for all dois in dois_list
bibtex_list = []
for doi in dois_list:
    bibtex = get_bibtex_from_doi(doi)
    bibtex_list.append(bibtex)
    print(bibtex)

 @article{Cornacchia_2023, title={Effects of Route Randomization on Urban Emissions}, volume={4}, ISSN={2750-4425}, url={http://dx.doi.org/10.52825/scp.v4i.217}, DOI={10.52825/scp.v4i.217}, journal={SUMO Conference Proceedings}, publisher={TIB Open Publishing}, author={Cornacchia, Giuliano and Nanni, Mirco and Pedreschi, Dino and Pappalardo, Luca}, year={2023}, month=jun, pages={75–87} }

 @article{Setzu_2024, title={Explainable Authorship Identification in Cultural Heritage Applications}, volume={17}, ISSN={1556-4711}, url={http://dx.doi.org/10.1145/3654675}, DOI={10.1145/3654675}, number={3}, journal={Journal on Computing and Cultural Heritage}, publisher={Association for Computing Machinery (ACM)}, author={Setzu, Mattia and Corbara, Silvia and Monreale, Anna and Moreo, Alejandro and Sebastiani, Fabrizio}, year={2024}, month=jun, pages={1–23} }

 @inbook{Corbucci_2023, title={Semantic Enrichment of Explanations of AI Models for Healthcare}, ISBN={9783031452758}, ISSN={1611-3349}, url={http://dx.doi.org/10.1007/978-3-031-45275-8_15}, DOI={10.1007/978-3-031-45275-8_15}, booktitle={Discovery Science}, publisher={Springer Nature Switzerland}, author={Corbucci, Luca and Monreale, Anna and Panigutti, Cecilia and Natilli, Michela and Smiraglio, Simona and Pedreschi, Dino}, year={2023}, pages={216–229} }

 @inbook{Cinquini_2023, title={Handling Missing Values in Local Post-hoc Explainability}, ISBN={9783031440670}, ISSN={1865-0937}, url={http://dx.doi.org/10.1007/978-3-031-44067-0_14}, DOI={10.1007/978-3-031-44067-0_14}, booktitle={Explainable Artificial Intelligence}, publisher={Springer Nature Switzerland}, author={Cinquini, Martina and Giannotti, Fosca and Guidotti, Riccardo and Mattei, Andrea}, year={2023}, pages={256–278} }

 @inbook{Guidotti_2023, title={Interpretable Data Partitioning Through Tree-Based Clustering Methods}, ISBN={9783031452758}, ISSN={1611-3349}, url={http://dx.doi.org/10.1007/978-3-031-45275-8_33}, DOI={10.1007/978-3-031-45275-8_33}, booktitle={Discovery Science}, publisher={Springer Nature Switzerland}, author={Guidotti, Riccardo and Landi, Cristiano and Beretta, Andrea and Fadda, Daniele and Nanni, Mirco}, year={2023}, pages={492–507} }

 @inbook{Corbucci_2023, title={Explaining Black-Boxes in Federated Learning}, ISBN={9783031440670}, ISSN={1865-0937}, url={http://dx.doi.org/10.1007/978-3-031-44067-0_8}, DOI={10.1007/978-3-031-44067-0_8}, booktitle={Explainable Artificial Intelligence}, publisher={Springer Nature Switzerland}, author={Corbucci, Luca and Guidotti, Riccardo and Monreale, Anna}, year={2023}, pages={151–163} }

 @inbook{Serafim_2024, title={Exploring Large Language Models Capabilities to Explain Decision Trees}, ISBN={9781643685229}, ISSN={1879-8314}, url={http://dx.doi.org/10.3233/FAIA240183}, DOI={10.3233/faia240183}, booktitle={HHAI 2024: Hybrid Human AI Systems for the Social Good}, publisher={IOS Press}, author={Serafim, Paulo Bruno and Crescenzi, Pierluigi and Gezici, Gizem and Cappuccio, Eleonora and Rinzivillo, Salvatore and Giannotti, Fosca}, year={2024}, month=jun }

 @article{Peduzzi_2024, title={Analysis of exposome and genetic variability suggests stress as a major contributor for development of pancreatic ductal adenocarcinoma}, volume={56}, ISSN={1590-8658}, url={http://dx.doi.org/10.1016/j.dld.2023.10.015}, DOI={10.1016/j.dld.2023.10.015}, number={6}, journal={Digestive and Liver Disease}, publisher={Elsevier BV}, author={Peduzzi, Giulia and Felici, Alessio and Pellungrini, Roberto and Giorgolo, Francesca and Farinella, Riccardo and Gentiluomo, Manuel and Spinelli, Andrea and Capurso, Gabriele and Monreale, Anna and Canzian, Federico and Calderisi, Marco and Campa, Daniele}, year={2024}, month=jun, pages={1054–1063} }

 @inbook{Lenders_2024, title={Interpretable and Fair Mechanisms for Abstaining Classifiers}, ISBN={9783031703683}, ISSN={1611-3349}, url={http://dx.doi.org/10.1007/978-3-031-70368-3_25}, DOI={10.1007/978-3-031-70368-3_25}, booktitle={Machine Learning and Knowledge Discovery in Databases. Research Track}, publisher={Springer Nature Switzerland}, author={Lenders, Daphne and Pugnana, Andrea and Pellungrini, Roberto and Calders, Toon and Pedreschi, Dino and Giannotti, Fosca}, year={2024}, pages={416–433} }

 @inbook{Fernandez_2024, title={FLocalX - Local to Global Fuzzy Explanations for Black Box Classifiers}, ISBN={9783031585531}, ISSN={1611-3349}, url={http://dx.doi.org/10.1007/978-3-031-58553-1_16}, DOI={10.1007/978-3-031-58553-1_16}, booktitle={Advances in Intelligent Data Analysis XXII}, publisher={Springer Nature Switzerland}, author={Fernandez, Guillermo and Guidotti, Riccardo and Giannotti, Fosca and Setzu, Mattia and Aledo, Juan A. and Gámez, Jose A. and Puerta, Jose M.}, year={2024}, pages={197–209} }

 @inbook{Corbucci_2023, title={Explaining Black-Boxes in Federated Learning}, ISBN={9783031440670}, ISSN={1865-0937}, url={http://dx.doi.org/10.1007/978-3-031-44067-0_8}, DOI={10.1007/978-3-031-44067-0_8}, booktitle={Explainable Artificial Intelligence}, publisher={Springer Nature Switzerland}, author={Corbucci, Luca and Guidotti, Riccardo and Monreale, Anna}, year={2023}, pages={151–163} }

 @inbook{Guidotti_2023, title={Interpretable Data Partitioning Through Tree-Based Clustering Methods}, ISBN={9783031452758}, ISSN={1611-3349}, url={http://dx.doi.org/10.1007/978-3-031-45275-8_33}, DOI={10.1007/978-3-031-45275-8_33}, booktitle={Discovery Science}, publisher={Springer Nature Switzerland}, author={Guidotti, Riccardo and Landi, Cristiano and Beretta, Andrea and Fadda, Daniele and Nanni, Mirco}, year={2023}, pages={492–507} }

 @inbook{Mazzoni_2024, title={A Frank System for Co-Evolutionary Hybrid Decision-Making}, ISBN={9783031585531}, ISSN={1611-3349}, url={http://dx.doi.org/10.1007/978-3-031-58553-1_19}, DOI={10.1007/978-3-031-58553-1_19}, booktitle={Advances in Intelligent Data Analysis XXII}, publisher={Springer Nature Switzerland}, author={Mazzoni, Federico and Guidotti, Riccardo and Malizia, Alessio}, year={2024}, pages={236–248} }

 @article{Fedele_2024, title={Explaining Siamese networks in few-shot learning}, volume={113}, ISSN={1573-0565}, url={http://dx.doi.org/10.1007/s10994-024-06529-8}, DOI={10.1007/s10994-024-06529-8}, number={10}, journal={Machine Learning}, publisher={Springer Science and Business Media LLC}, author={Fedele, Andrea and Guidotti, Riccardo and Pedreschi, Dino}, year={2024}, month=apr, pages={7723–7760} }