# Conversione Pubblicazioni da Google Sheets a HTML

Questo notebook legge i dati delle pubblicazioni da un Google Sheet e li converte in formato HTML/Pug per il sito web del progetto XAI.

In [1]:
import pandas as pd
from IPython.display import HTML
import math

## Librerie necessarie

Import delle librerie utilizzate nel notebook.

In [2]:
import inflect
p = inflect.engine()
p.number_to_words(99)

'ninety-nine'

In [3]:
import urllib.request
from urllib.error import HTTPError
import sys

## Ottenere lo Sheet ID

Lo `sheet_id` è una stringa univoca che identifica un Google Sheet. Può essere ottenuto dall'URL del Google Sheet. Ad esempio, se l'URL del Google Sheet è:
'https://docs.google.com/spreadsheets/d/1A2B3C4D5E6F7G8H9I0J1K2L3M4N5O6P7Q8R9S0T1U2V3W4X5Y6Z7/edit#gid=0'

allora lo `sheet_id` è `1A2B3C4D5E6F7G8H9I0J1K2L3M4N5O6P7Q8R9S0T1U2V3W4X5Y6Z7`.


## Configurazione Google Sheets API

Per accedere ai dati del Google Sheet, è necessario configurare l'accesso tramite le API di Google Sheets. 
Seguire i passaggi indicati nella documentazione ufficiale per ottenere le credenziali necessarie.

In [4]:
sheet_id = '1VaF5jAauYYYKo1WH40kLlsQ0-azIX5eMZoFYv5JrVr0' # XAI-publications RP4 (sostituire con il proprio sheet ID RP5)
sheet_id = '1xhwFSi5CHSOKIovYVdLidgxo_JjW8WkH' #XAI-publications RP5
sheet_names = ['papers','dataset','algorithms','masterThesis','phdThesis']

## Configurazione Google Sheets

Definizione dell'ID del Google Sheet e dei nomi dei fogli da cui leggere i dati.

In [5]:
def write_html(string,filename='filename',extension='html'):
    Html_file= open(f"{filename}.{extension}","w")
    Html_file.write(string)
    Html_file.close()

## Funzione di utilità

Funzione per scrivere stringhe HTML in file.

## Papers

In [6]:
sheet_name= sheet_names[0]
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [7]:
papers = pd.read_csv(url,header=0)
papers.columns

Index(['Id in EU', 'id', 'Id di Riccardo', 'In zotero', 'EU selection',
       'Title of the scientific publication', 'abstract', 'doi link', 'DOI',
       'Year of publication', 'Type of scientific publication', 'Issue',
       'visible on website', 'selected', 'Ack', 'Open access',
       'Open Access Fee', 'Fee corrisposta da', 'container', 'Publisher',
       'Authors', 'ISSN or eSSN', 'Title of the journal or equivalent',
       'Number, date', 'Place of publication', 'Relevant pages',
       'Joint Public / Private publication', 'Peer-review', 'Research line'],
      dtype='object')

### Caricamento dati papers

Lettura del foglio "papers" dal Google Sheet.

In [8]:
aut= []
for i,el in papers.iterrows():
    l = [x.strip() for x in el.Authors.split(',')]
    aut.append(l)
flat_list = sum(aut, [])
authorsU =list(set(flat_list))
print(authorsU, len(authorsU))

['Riccardo Farinella', 'A.', 'Panigutti Cecilia', 'Marta Marchiori Manerba', 'Minervini Pasquale', 'Aleksandra Maslennikova', 'Isabel Valera', 'Stefano Tramacere', 'Pappalardo Luca', 'Jacopo Joy Colombini', 'Himanshi Allahabadi', 'Luca Alessandro Cappellini', 'Mario Alfonso Prado-Romero', 'Sema Candemir', 'David Sánchez', 'Renee Wurth', 'Fabio Zanasi', 'Filippo Bonchi', 'Marchiori Manerba Marta', 'Panigutti', 'Genevieve Fieux-Castagnet', 'Valerio Bonsignori', 'Karolina Stanczak', 'Fernanda Oliveira Gomes', 'Tommaso Cucinotta', 'Antonio Bencini Farina', 'Monreale Anna', 'Francesco Giannini', 'Voukelatou Vasiliki', 'Stephanie Law', 'Luca Nannini', 'Mattia Savardi', 'Fadda', 'S Rinzivillo', 'Freddy Lecue', 'Guya Giuliani', 'Jose M. Alvarez', 'Eleonora Cappuccio', 'Piaggesi Simone', 'Bodria Francesco', 'Nicolò Navarin', 'G. Ercoli', 'Nicoleta Cherciu', 'Yuan Yin', 'Laura State', 'Stefano Fioravanti', 'Paulo Bruno Serafim', 'Tina Eliassi-Rad', 'Andrea Fedele', 'M. Di Vece', 'Frederick Bruneault', 'Udo Schlegel', 'Francesco Spinnato', 'Piotr Wilczyński', 'Pedro A. Moreno-Sanchez', 'Diego Garlaschelli', 'Veloso Bruno', 'Fabio Michele Russo', 'Michela Natilli', 'Alessio Felici', 'Toon Calders', 'Wojciech Samek', 'Giulia Volpi', 'Dino Pedreschi', 'Giuliano Cornacchia', 'Gallinari Patrick', 'Bajardi Paolo', 'Simone Piaggesi', 'Giannotti', 'Alexandre Santos', 'Franco Turini', 'Franco Raimondi', 'C Metta', 'Fedele Andrea', 'Daniele; Guidotti', 'Romula Ferrer Filho', 'Samuele Tonati', 'Yoichi Hayashi', 'G. Barlacchi', 'Maccagnola Daniele', 'Simone Stumpf', 'Gianclaudio Malgieri', 'Andrea Beretta', 'Lampridis Orestis', 'Brogi Antonio', 'Daniele Maccagnola', 'Silvia Corbara', 'Patrizio Frosini', 'Mattia Cerrato', 'Matiss Ozols', 'Lau Bee Theng', 'Jesmin Jahan Tithi', 'Fisher Michael', 'Lucia Passaro', 'Rodrigo Castellano Ontiveros', 'Praveen Bushipaka', 'Paciello Giulia', 'A Beretta', 'Caroprese Luciano', 'Lorenzo', 'Giulia Peduzzi', 'Frank P. Pijpers', 'Y Yin', 'Pedreschi', 'Maciej Krzysztof Zuziak', 'Cecilia Panigutti', 'Rosa Lanzilotti', 'Isabelle Augenstein', 'Bardh Prenkaj', 'Giovanni Sartor', 'Salvatore; Fadda', 'Gezici', 'Roberto Pellungrini', 'Dino', 'Pietro Barbiero', 'James Brusseau', 'Bonsignori Valerio', 'Dignum Virginia', 'Beretta Andrea', 'Luca Pappalardo', 'Francesca Pratesi', 'A. Mastropietro', 'Alessio Malizia', 'Sami Zhioua', 'Turini Franco', 'L. Pappalardo', 'Neri Davide', 'Sune Holm', 'Martina Cinquini', 'Mirco Nanni', 'Manuel Gentiluomo', 'Aniek F. Markus', 'Jean Everson Martina', 'André Panisson', 'Morini Virginia', 'Andrés Páez', 'Jonas Bozenhard', 'Andrea Ceni', 'Roberto Confalonieri', 'Andrea Passarella', 'Filippo Vaccher', 'Manco Giuseppe', 'Stefano Melacci', 'Mario Brcic', 'Daniele Campa', 'Gezici G.; Metta C; Beretta A.; Pellungrini R.; Rinzivillo S.; Pedreschi D.; Giannotti F.', 'Mattia Proietti', 'Setzu Mattia', 'Alejandra Bringas Colmenarejo', 'Ruggieri Salvatore', 'P Gallinari', 'Leonardo Espinosa-Leal', 'Alex Sandy Pentland', 'Matwin Stan', 'Bacciu Davide', 'Davide Farina', 'Avishek Anand', 'Michelangelo Diligenti', 'Alessandro Vespignani', 'Salvatore Rinzivillo', 'Andrea Pugnana', 'Alessio Cascione', 'Megha Khosla', 'Metta Carlo', 'Marco Gori', 'E. Ferragina', 'Pierluigi Crescenzi', 'Bodria', 'Chiara Renso', 'Nanni Mirco', 'Roberto V. Zicari', 'A. Iommi', 'Pedreschi Dino', 'Minici Marco', 'Dawid Płudowski', 'Mario Bianchi', 'Hanna-Maria Sormunen', 'Debora Nozza', 'Andrea Rafanelli; Stefania Costantini; Andrea Omicini', 'Andrea Spinelli', 'Cariaggi Leonardo', 'D.', 'Krzysztof Kotowski', 'D. Garlaschelli', 'Ana Rita Nogueira', 'Josep Domingo-Ferrer', 'Naretto Francesca', 'Fedele A.', 'Chiara; Orlandi', 'Thomas Frauenfelder', 'Giannotti Fosca', 'John Shawe-Taylor', 'Irmhild van Halem', 'Yin Yuan', 'Steven Umbrello', 'Guidotti Riccardo', 'Guillermo Fernandez', 'Andrea Cossu', 'Brendan Parent', 'Gabriele Dominici', 'Catuscia Palamidessi', 'Francisco Herrera', 'Juan A. Aledo', 'Marzio Di Vece', 'Margherita Lalli', 'Fabio Pinelli', 'Fadda Daniele', 'Musolesi Mirco', 'Panisson André', 'Gabriele Capurso', 'Mattia Setzu', 'Riccardo; Giannotti', 'Carlo Metta', 'A. Ferraro', 'A. Monreale', 'Simona Smiraglio', 'Emanuele Neri', 'Landi Cristiano', 'S.', 'Federico A. Galatolo', 'Virginia Dignum', 'Emilie Wiinblad Mathez', 'Clara Punzi', 'Alberto Signoroni', 'Chatila Raja', 'Annette F. Stephansen', 'Mattia Poggioli', 'Luc De Raedt', 'Salvatore Ruggieri', 'Pasquale Minervini', 'Megan Coffee', 'Marta Marchiori Manerba and Riccardo Guidotti', 'Emanuele Ferragina', 'Fosca; Pedreschi', 'Francesca Naretto', 'Luca Longo', 'Jaesik Choi', 'Julia Amann', 'Spinnato Francesco', 'Riccardo Massidda', 'Magnus Westerlund', 'Morik Katharina', 'Timo Speith', 'Alessandro Lenci', 'Serg Masis', 'Hassan Khosravi', 'Mateo Espinosa Zarlenga', 'Gizem; Mannari', 'Christian Di Maio', 'Javier Alejandro Borges Legrottaglie', 'Andreas Theissler', 'Chandana Sree Mala', 'D. Rotelli', 'F.', 'Alessio Gallucci', 'Isacco Beretta', 'Ricardo Baeza-Yates', 'Subrata Chakraborty', 'Davide Bacciu', 'Federico Mazzoni', 'Giovanni Mauro', 'Evridiki Vasileia Ntagiou', 'M. Lalli', 'Rinzivillo Salvatore', 'Miliou Ioanna', 'S. Ruggieri', 'Jarno Tuominen', 'János Kertész', 'Fosca Giannotti & Dino Pedreschi', 'Xenia Heilmann', 'Francesco Mureddu', 'Daniele Gambetta', 'Christina Cociancig', 'Javier Del Ser', 'Soldani Jacopo', 'Alistair Knott', 'João Gama', 'Gizem Gezici', 'Riccardo Guidotti', 'Andrea Mattei', 'Adam Golda', 'Yannis Ioannidis', 'Karima Makhlouf', 'Benedetta Muscato', 'Albert-László Barabási', 'Russell Stuart', 'Dennis Vetter', 'Claudio Gallicchio', 'Marco Calderisi', 'Resta Michele', 'Anna Monreale', 'Federico Canzian', 'Johannes Schneider', 'Giovanni Stilo', 'Frank Dignum', 'F Giannotti', 'F. Giannotti', 'Gama Joao', 'Przemysław Biecek', 'Pellungrini Roberto', 'R Guidotti', 'Francesco; Rinzivillo', 'Bosi Emanuele', 'Matteo D’Onofrio', 'Federico Cabitza', 'Paolo Frazzetto', 'Virginia Morini', 'Laura Pollacci', 'Giuseppe Marra', 'Elisabeth Hildt', 'Luca Corbucci', 'Alejandro Moreo', 'Sebastien A. Krier', 'Perotti Alan', 'C.', 'Ulrich Kuhne', 'Paul Lukowicz', 'Francesco Bodria', 'Rinzivillo', 'Liguori Angelica', 'Walter Osika', 'Giulio Rossetti', 'Matteo Böhm', 'A. Beretta', 'Valentina Pansanella', 'Nardini Franco Maria', 'Pugnana Andrea', 'Isabelle Balot', 'R. Guidotti', 'Perotti', 'Charles Binkley', 'Fabrizio Sebastiani', 'Salvatore Citraro', 'Mario G. C. A. Cimino', 'Yeung Karen', 'Adarsh Srivastava', 'Ying Jiao', 'Rami Haffar', 'Patrick Gallinari', 'Andy Spezzatti', 'Irene Ek', 'Daniele Fadda', 'Beretta I; Cappuccio E; Marchiori Manerba M', 'Richard Jiang', 'Georgios Kararigas', 'Orestis Lampridis', 'Vince I. Madai', 'T. Squartini', 'Daphne Lenders', 'Andreas Holzinger', 'Comandè Giovanni', 'Francesca Giorgolo', 'Jose A. Gámez et al.', 'Francesca Tria', 'STENIO Freitas', 'Fosca Giannotti', 'Cristiano Landi', 'Giulio Tani Raffaelli', 'Bencini Farina Antonio', 'Beretta', 'Francesca Lizzi'] 361

# Filtra i lavori per `visible on website`

In [9]:
papers = papers[papers["visible on website"]=="YES"]
papers

,Id in EU,id,Id di Riccardo,In zotero,EU selection,Title of the scientific publication,abstract,doi link,DOI,Year of publication,...,Publisher,Authors,ISSN or eSSN,Title of the journal or equivalent,"Number, date",Place of publication,Relevant pages,Joint Public / Private publication,Peer-review,Research line
0,1.0,24,GMG2019,True,True,Factual and Counterfactual Explanations for Bl...,The rise of sophisticated machine learning mod...,https://dx.doi.org/10.1109/mis.2019.2957223,10.1109/MIS.2019.2957223,2021,...,Institute of Electrical and Electronics Engine...,"Guidotti Riccardo, Monreale Anna, Giannotti Fo...",1541-1672,IEEE Intelligent Systems,NaN,NaN,14-23,NO,NaN,"1,4"
1,2.0,23,SGM2021,True,True,GLocalX - From Local to Global Explanations of...,Artificial Intelligence (AI) has come to promi...,https://dx.doi.org/10.1016/j.artint.2021.103457,10.1016/j.artint.2021.103457,2021,...,Elsevier BV,"Setzu Mattia, Guidotti Riccardo, Monreale Anna...",0004-3702,Artificial Intelligence,NaN,NaN,NaN,NO,YES,"1,4"
2,3.0,35,GMS2020,True,True,Explaining Any Time Series Classifier,We present a method to explain the decisions o...,https://dx.doi.org/10.1109/cogmi50398.2020.00029,10.1109/CogMI50398.2020.00029,2020,...,IEEE,"Guidotti Riccardo, Monreale Anna, Spinnato Fra...",NaN,NaN,2020,NaN,NaN,NaN,NaN,1
3,4.0,18,NPN2020,True,False,Prediction and Explanation of Privacy Risk on ...,The analysis of privacy risk for mobility data...,https://dx.doi.org/10.1007/978-3-030-65965-3_34,10.1007/978-3-030-65965-3_34,2021,...,Springer International Publishing,"Naretto Francesca, Pellungrini Roberto, Nardin...",1865-0929,ECML PKDD 2020 Workshops,NaN,NaN,NaN,NO,YES,"4,5"
4,5.0,17,NPM2020,True,False,Predicting and Explaining Privacy Risk Exposur...,Mobility data is a proxy of different social d...,https://dx.doi.org/10.1007/978-3-030-61527-7_27,10.1007/978-3-030-61527-7_27,2021,...,Springer International Publishing,"Naretto Francesca, Pellungrini Roberto, Monrea...",0302-9743,Discovery Science Conference,NaN,NaN,403-418,NO,YES,"4,5"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,NaN,152,CGG2023,True,False,Handling Missing Values in Local Post-hoc Expl...,Missing data are quite common in real scenario...,https://doi.org/10.1007/978-3-031-44067-0_14,10.1007/978-3-031-44067-0_14,2023,...,NaN,"Martina Cinquini, Fosca Giannotti, Riccardo Gu...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
157,NaN,153,LCM2025c,True,False,Implicit Neural Decision Trees,The revolution involving Machine Learning has ...,https://doi.org/10.1007/978-3-032-08324-1_5,10.1007/978-3-032-08324-1_5,2025,...,NaN,"Cristiano Landi, Alessio Cascione, Marta March...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
159,NaN,163,BLF2025,NaN,False,A Simulation Framework for Studying Systemic E...,Recommender systems continuously interact with...,https://doi.org/10.48550/arXiv.2510.14857,10.48550/arXiv.2510.14857,2025,...,NaN,"G. Barlacchi, M. Lalli, E. Ferragina, F. Giann...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
160,121.0,164,PPF2025,True,True,Human-AI coevolution,"Human-AI coevolution, defined as a process in ...",https://doi.org/10.1016/j.artint.2024.104244,10.1016/j.artint.2024.104244,2025,...,Elsevier BV,"Dino Pedreschi, Luca Pappalardo, Emanuele Ferr...",43702,Artificial Intelligence,339,Netherlands,104244,NaN,NaN,1
161,122.0,165,NaN,True,True,Explaining short text classification with dive...,"We present xspells, a model-agnostic local app...",https://link.springer.com/article/10.1007/s109...,10.1016/j.artint.2024.104244,2022,...,Kluwer Academic Publishers,"Orestis Lampridis, Laura State, Riccardo Guido...",8856125,Machine Learning,112,Netherlands,4289-4322,NaN,NaN,2

### Estrazione autori unici

Analisi degli autori presenti nelle pubblicazioni.

In [10]:
if '1' in (papers['Research line'][0]).split(','):
    print('eccolo')

eccolo

In [11]:
lines = [*range(1,6,1)]
lines

[1, 2, 3, 4, 5]

## Visualization order of the papers

In [12]:
papers=papers.sort_values(by=['Year of publication'], ascending = False).reset_index(drop=True)

In [13]:
bullets='<ul>'
for i, row in papers.iterrows():
    authors= row['Authors']
#     pubblicationYear = int(row['Year of publication'])
    pubYearString = row['Year of publication']
    pubblicationYear =  '.' if pubYearString!=pubYearString else ' - '+str(int(pubYearString))+' -'
    title=row['Title of the scientific publication'].strip('.')
    
    journalString=row['Title of the journal or equivalent']
    journal='.' if journalString!=journalString else ', '+journalString.strip()+'.'
    DOI=row['DOI']
    
    bullet=f"<li><strong><a href='https://doi.org/{DOI}' target='_blank'>{title}</a></strong>{pubblicationYear} {authors} {journal}</li>"
    if row['visible on website'] == 'YES':
        bullets+=bullet
bullets+='</ul>'
display(HTML(bullets))

### Generazione lista HTML

Generazione della lista HTML delle pubblicazioni con link ai DOI.

In [14]:
papers=papers.sort_values(by=['Year of publication'], ascending = False).reset_index(drop=True)
papers

,Id in EU,id,Id di Riccardo,In zotero,EU selection,Title of the scientific publication,abstract,doi link,DOI,Year of publication,...,Publisher,Authors,ISSN or eSSN,Title of the journal or equivalent,"Number, date",Place of publication,Relevant pages,Joint Public / Private publication,Peer-review,Research line
0,104.0,125,CBR2025,True,True,A Practical Approach to Causal Inference over ...,"In this paper, we focus on estimating the caus...",https://doi.org/10.1609/aaai.v39i14.33626,10.1609/aaai.v39i14.33626,2025,...,NaN,"Martina Cinquini, Isacco Beretta, Salvatore Ru...","2374-3468, 2159-5399",Proceedings of the AAAI Conference on Artifici...,39,NaN,14832--14839,NaN,NaN,2
1,102.0,123,MBG2025,True,True,Embracing Diversity: A Multi-Perspective Appro...,"In subjective tasks like stance detection, div...",https://doi.org/10.3233/FAIA250654,10.3233/FAIA250654,2025,...,NaN,"Benedetta Muscato, Praveen Bushipaka, Gizem Ge...",NaN,Frontiers in Artificial Intelligence and Appli...,NaN,NaN,370--384,NaN,NaN,"4,5"
2,114.0,158,CMM2025,True,True,SafeGen: safeguarding privacy and fairness thr...,To ensure that Machine Learning systems produc...,https://doi.org/10.1007/s10994-025-06835-9,10.1007/s10994-025-06835-9,2025,...,NaN,"Martina Cinquini, Marta Marchiori Manerba, Fed...",NaN,Machine Learning,114,NaN,NaN,NaN,NaN,5
3,NaN,127,CMZ2025,True,False,A Bias Injection Technique to Assess the Resil...,Causal discovery (CD) algorithms are increasin...,https://doi.org/10.1109/ACCESS.2025.3573201,10.1109/ACCESS.2025.3573201,2025,...,NaN,"Martina Cinquini, Karima Makhlouf, Sami Zhioua...",2169-3536,IEEE Access,2025-06-06,NaN,1--1,NaN,NaN,"2,5"
4,NaN,129,BCN2025,NaN,False,Differentially Private FastSHAP for Federated ...,Explaining the reasoning behind black-box mode...,NaN,10.1109/IJCNN64981.2025.11227553,2025,...,NaN,"Valerio Bonsignori, Luca Corbucci, Francesca N...",NaN,NaN,NaN,"Rome, Italy",NaN,NaN,NaN,"1,5"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,9.0,6,GM2020,True,True,Data-Agnostic Local Neighborhood Generation,Synthetic data generation has been widely adop...,https://ieeexplore.ieee.org/document/9338395,10.1109/ICDM50108.2020.00122,2020,...,IEEE,"Guidotti Riccardo, Monreale Anna",2374-8486,2020 IEEE International Conference on Data Min...,2020,NaN,NaN,NaN,NaN,1
137,3.0,35,GMS2020,True,True,Explaining Any Time Series Classifier,We present a method to explain the decisions o...,https://dx.doi.org/10.1109/cogmi50398.2020.00029,10.1109/CogMI50398.2020.00029,2020,...,IEEE,"Guidotti Riccardo, Monreale Anna, Spinnato Fra...",NaN,NaN,2020,NaN,NaN,NaN,NaN,1
138,NaN,3,GMP2019,NaN,False,The AI black box explanation problem,The use of machine learning in decision-making...,https://ercim-news.ercim.eu/images/stories/EN1...,NaN,2019,...,ERCIM – the European Research Consortium for I...,"Guidotti Riccardo, Monreale Anna, Pedreschi Dino",NaN,"ERCIM News, 116, 12-13",2019,NaN,NaN,NaN,NaN,"1,2,3"
139,NaN,2,PGG2018,NaN,False,Open the Black Box Data-Driven Explanation of ...,Black box systems for automated decision makin...,https://arxiv.org/abs/1806.09936,1806.09936,2018,...,Arxive,"Pedreschi Dino, Giannotti Fosca, Guidotti Ricc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
140,NaN,1,GMR2018a,NaN,False,Local Rule-Based Explanations of Black Box Dec...,The recent years have witnessed the rise of ac...,https://arxiv.org/abs/1805.10820,1805.10820,2018,...,Arxive,"Guidotti Riccardo, Monreale Anna, Ruggieri Sal...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

# DOI TO BibTex

### Conversione DOI in BibTeX

Test di conversione di un singolo DOI in formato BibTeX.

In [15]:
import time
import sys
import urllib.request
from urllib.error import URLError, HTTPError

doi = '10.1007/978-3-030-10997-4_13'

# Endpoint Crossref
BASE_URL = 'https://api.crossref.org/works/'
url = f'{BASE_URL}{doi}/transform/application/x-bibtex'

max_retries = 5
retry_delay = 1  # Initial delay in seconds

for attempt in range(max_retries):
    try:
        req = urllib.request.Request(url)
        # Qui in teoria non serve neanche l'Accept, ma non fa male
        req.add_header('Accept', 'application/x-bibtex')
        req.add_header(
            'User-Agent',
            'bibtex-fetcher/1.0 (mailto:tuo.nome@esempio.it)'
        )

        # puoi anche provare a portare il timeout a 30s per test
        with urllib.request.urlopen(req, timeout=30) as f:
            bibtex = f.read().decode('utf-8')

        print(bibtex)
        break

    except HTTPError as e:
        if e.code == 404:
            print('DOI not found.')
            sys.exit(1)
        else:
            print(f'Service unavailable (HTTP {e.code}). Retrying...')

    except URLError as e:
        print(f'Network error: {e.reason}. Retrying...')

    except ConnectionResetError:
        print('Connection reset by peer. Retrying...')

    time.sleep(retry_delay)
    retry_delay *= 2

else:
    print('Failed to retrieve the BibTeX after multiple attempts.')
    sys.exit(1)

print(type(bibtex))
print(url)

 @inbook{Guidotti_2019, title={Helping Your Docker Images to Spread Based on Explainable Models}, ISBN={9783030109974}, ISSN={1611-3349}, url={http://dx.doi.org/10.1007/978-3-030-10997-4_13}, DOI={10.1007/978-3-030-10997-4_13}, booktitle={Machine Learning and Knowledge Discovery in Databases}, publisher={Springer International Publishing}, author={Guidotti, Riccardo and Soldani, Jacopo and Neri, Davide and Brogi, Antonio and Pedreschi, Dino}, year={2019}, pages={205–221} }

<class 'str'>
https://api.crossref.org/works/10.1007/978-3-030-10997-4_13/transform/application/x-bibtex

### Conversione batch DOI a BibTeX

Conversione di tutti i DOI delle pubblicazioni in formato BibTeX.

In [16]:
import urllib.request
from urllib.error import URLError, HTTPError

bibs = []   # Voci BibTeX recuperate
bib_indices = []   # Indici delle righe CSV corrispondenti
failed_doi_indices = []  # Indici dei DOI non recuperati

# Endpoint Crossref robusto
BASE_URL = 'https://api.crossref.org/works/'

# User-Agent obbligatorio per evitare blocchi
HEADERS = {
    'Accept': 'application/x-bibtex',
    'User-Agent': 'bibtex-fetcher/1.0 (mailto:tuo.nome@esempio.it)'
}

for i, doi in enumerate(papers.DOI.to_list()):
    if isinstance(doi, str) and doi.strip() != "":
        
        # Costruzione URL Crossref
        url = f"{BASE_URL}{doi}/transform/application/x-bibtex"

        print(f"→ [{i+1}] Fetch DOI: {doi}")

        req = urllib.request.Request(url, headers=HEADERS)

        try:
            # Timeout più alto per DOI lenti
            with urllib.request.urlopen(req, timeout=20) as f:
                bibtex = f.read().decode('utf-8')

            bibs.append(bibtex)
            bib_indices.append(i)
            print(f"   ✓ OK")

        except HTTPError as e:
            print(f"   ✗ HTTP error (code {e.code}) per DOI {doi}")
            if e.code == 404:
                print("     → DOI not found su Crossref.")
            else:
                print("     → Server error.")
            failed_doi_indices.append(i)

        except URLError as e:
            print(f"   ✗ Network error per DOI {doi}: {e.reason}")
            failed_doi_indices.append(i)

        except Exception as e:
            print(f"   ✗ Errore imprevisto per DOI {doi}: {e}")
            failed_doi_indices.append(i)

    else:
        print(f"⊘ [{i+1}] DOI mancante o non valido")
        failed_doi_indices.append(i)

print("\n" + "="*60)
print(f"Recuperati {len(bibs)} BibTeX su {len(papers)} papers totali")
print(f"DOI falliti o mancanti: {len(failed_doi_indices)}")
if failed_doi_indices:
    print(f"Indici dei DOI falliti/mancanti: {failed_doi_indices}")
print("="*60)

→ [1] Fetch DOI: 10.1609/aaai.v39i14.33626
   ✓ OK
→ [2] Fetch DOI: 10.3233/FAIA250654
   ✓ OK
→ [3] Fetch DOI: 10.1007/s10994-025-06835-9
   ✓ OK
→ [4] Fetch DOI: 10.1109/ACCESS.2025.3573201
   ✓ OK
→ [5] Fetch DOI: 10.1109/IJCNN64981.2025.11227553
   ✓ OK
⊘ [6] DOI mancante o non valido
→ [7] Fetch DOI: 10.1613/jair.1.17935
   ✓ OK
⊘ [8] DOI mancante o non valido
→ [9] Fetch DOI: 10.48550/arXiv.2410.21043
   ✗ HTTP error (code 404) per DOI 10.48550/arXiv.2410.21043
     → DOI not found su Crossref.
→ [10] Fetch DOI: 10.1007/978-3-032-08324-1_5
   ✓ OK
⊘ [11] DOI mancante o non valido
→ [12] Fetch DOI: 10.48550/arXiv.2510.14857
   ✗ HTTP error (code 404) per DOI 10.48550/arXiv.2510.14857
     → DOI not found su Crossref.
→ [13] Fetch DOI: 10.1016/j.artint.2024.104244
   ✓ OK
⊘ [14] DOI mancante o non valido
⊘ [15] DOI mancante o non valido
→ [16] Fetch DOI: 10.1007/978-3-032-06078-5_6
   ✓ OK
⊘ [17] DOI mancante o non valido
→ [18] Fetch DOI: 10.1007/978-3-032-08324-1_13
   ✓ OK
→ [19] Fetch DOI: 10.1007/978-3-031-78980-9_11
   ✓ OK
→ [20] Fetch DOI: 10.1007/978-3-032-08324-1_5
   ✓ OK
→ [21] Fetch DOI: 10.3233/FAIA250637
   ✓ OK
→ [22] Fetch DOI: 10.24963/ijcai.2025/1092
   ✓ OK
→ [23] Fetch DOI: 10.24963/kr.2025/30
   ✓ OK
→ [24] Fetch DOI: 10.3233/FAIA250912
   ✓ OK
→ [25] Fetch DOI: 10.3233/FAIA250902
   ✓ OK
⊘ [26] DOI mancante o non valido
⊘ [27] DOI mancante o non valido
→ [28] Fetch DOI: 10.1007/978-3-031-78980-9_21
   ✓ OK
→ [29] Fetch DOI: 10.1007/s10506-024-09430-w
   ✓ OK
→ [30] Fetch DOI: 10.1007/978-3-032-06078-5_1
   ✓ OK
→ [31] Fetch DOI: 10.1007/978-3-032-08327-2_8
   ✓ OK
→ [32] Fetch DOI: 10.14428/esann/2024.es2024-78
   ✓ OK
→ [33] Fetch DOI: 10.1016/j.clsr.2024.105986
   ✓ OK
→ [34] Fetch DOI: 10.1109/access.2024.3464743
   ✓ OK
→ [35] Fetch DOI: 10.1109/BigData62323.2024.10825763
   ✓ OK
⊘ [36] DOI mancante o non valido
⊘ [37] DOI mancante o non valido
→ [38] Fetch DOI: 10.48550/arXiv.2407.01630
   ✗ HTTP error (code 404) per DOI 10.48550/arXiv.2407.01630
     → DOI not found su Crossref.
⊘ [39] DOI mancante o non valido
→ [40] Fetch DOI: 10.21203/rs.3.rs-5369626/v1
   ✓ OK
→ [41] Fetch DOI: 10.1109/tkde.2024.3425460
   ✓ OK
⊘ [42] DOI mancante o non valido
⊘ [43] DOI mancante o non valido
⊘ [44] DOI mancante o non valido
→ [45] Fetch DOI: 10.18653/v1/2024.trustnlp-1.3
   ✓ OK
→ [46] Fetch DOI: 10.1145/3618105
   ✓ OK
→ [47] Fetch DOI: 10.1007/978-3-031-58553-1_16
   ✓ OK
→ [48] Fetch DOI: 10.1038/s42005-024-01714-6
   ✓ OK
→ [49] Fetch DOI: 10.1609/aaai.v37i13.26925
   ✓ OK
→ [50] Fetch DOI: 10.3233/faia240184
   ✓ OK
→ [51] Fetch DOI: 10.1145/3654675
   ✓ OK
→ [52] Fetch DOI: 10.1016/j.inffus.2024.102301
   ✓ OK
→ [53] Fetch DOI: 10.3390/bioengineering11040369
   ✓ OK
→ [54] Fetch DOI: 10.1007/978-3-031-70341-6_22
   ✓ OK
→ [55] Fetch DOI: 10.1016/j.neucom.2024.127960
   ✓ OK
→ [56] Fetch DOI: 10.3390/diagnostics14070753
   ✓ OK
→ [57] Fetch DOI: 10.18653/v1/2024.emnlp-main.812
   ✓ OK
→ [58] Fetch DOI: 10.1007/s10676-024-09773-7
   ✓ OK
→ [59] Fetch DOI: 10.1007/978-3-031-63800-8_6
   ✓ OK
→ [60] Fetch DOI: 10.1038/s41598-024-53655-3
   ✓ OK
→ [61] Fetch DOI: 10.1007/978-3-031-58553-1_19
   ✓ OK
→ [62] Fetch DOI: [75,46,72,75,50,73,78].
   ✗ Errore imprevisto per DOI [75,46,72,75,50,73,78]. : URL can't contain control characters. '/works/[75,46,72,75,50,73,78]. /transform/application/x-bibtex' (found at least ' ')
→ [63] Fetch DOI: 10.3233/faia240183
   ✓ OK
→ [64] Fetch DOI: 10.1007/s10994-024-06529-8
   ✓ OK
→ [65] Fetch DOI: 10.1609/aaai.v38i19.30104
   ✓ OK
→ [66] Fetch DOI: 10.1109/fuzz-ieee60900.2024.10611878
   ✓ OK
→ [67] Fetch DOI: 10.1109/access.2024.3496114
   ✓ OK
→ [68] Fetch DOI: 10.1007/s10618-023-00933-9
   ✓ OK
→ [69] Fetch DOI: 10.52825/scp.v4i.217
   ✓ OK
→ [70] Fetch DOI: 10.1007/s41060-023-00401-z
   ✓ OK
→ [71] Fetch DOI: 10.1007/978-3-031-44067-0_31
   ✓ OK
→ [72] Fetch DOI: 10.1007/978-3-031-45275-8_33
   ✓ OK
→ [73] Fetch DOI: 10.1007/978-3-031-45275-8_16
   ✓ OK
→ [74] Fetch DOI: 10.1007/978-3-031-44064-9_22
   ✓ OK
→ [75] Fetch DOI: 10.1145/3624480
   ✓ OK
→ [76] Fetch DOI: 10.1007/978-3-031-43619-2_10
   ✓ OK
→ [77] Fetch DOI: 10.1007/978-3-031-45275-8_22
   ✓ OK
→ [78] Fetch DOI: 10.1016/j.dld.2023.10.015
   ✓ OK
→ [79] Fetch DOI: 10.1007/978-3-031-44064-9_16
   ✓ OK
→ [80] Fetch DOI: 10.1007/978-3-031-23618-1_32
   ✓ OK
→ [81] Fetch DOI: 10.1145/3605390.3610811
   ✓ OK
⊘ [82] DOI mancante o non valido
⊘ [83] DOI mancante o non valido
⊘ [84] DOI mancante o non valido
→ [85] Fetch DOI: 10.1103/PhysRevE.108.054301
   ✓ OK
→ [86] Fetch DOI: 10.1145/3587271
   ✓ OK
→ [87] Fetch DOI: 10.1007/978-3-031-44067-0_14
   ✓ OK
→ [88] Fetch DOI: 10.48550/ARXIV.2303.06067
   ✗ HTTP error (code 404) per DOI 10.48550/ARXIV.2303.06067
     → DOI not found su Crossref.
→ [89] Fetch DOI: 10.1007/978-3-031-30047-9_19
   ✓ OK
→ [90] Fetch DOI: 10.3233/FAIA220206
   ✓ OK
→ [91] Fetch DOI: 10.1145/3491102.3502104
   ✓ OK
→ [92] Fetch DOI: 10.2312/evs.20221098
   ✗ HTTP error (code 404) per DOI 10.2312/evs.20221098
     → DOI not found su Crossref.
→ [93] Fetch DOI: 10.1109/tts.2022.3195114
   ✓ OK
→ [94] Fetch DOI: 10.1007/s10618-022-00831-6
   ✓ OK
⊘ [95] DOI mancante o non valido
→ [96] Fetch DOI: 10.1007/978-3-031-18840-4_37
   ✓ OK
→ [97] Fetch DOI: 10.1007/978-3-031-18840-4_36
   ✓ OK
→ [98] Fetch DOI: 10.1109/cogmi56440.2022.00012
   ✓ OK
→ [99] Fetch DOI: 10.1007/978-3-031-18840-4_39
   ✓ OK
→ [100] Fetch DOI: 10.1109/CogMI52975.2021.00015
   ✓ OK
→ [101] Fetch DOI: 10.1002/widm.1449
   ✓ OK
→ [102] Fetch DOI: 10.1007/978-3-030-69128-8_2
   ✓ OK
→ [103] Fetch DOI: 10.1145/3236009
   ✓ OK
→ [104] Fetch DOI: 10.1145/3514094.3534170
   ✓ OK
→ [105] Fetch DOI: 10.1007/s10618-022-00878-5
   ✓ OK
→ [106] Fetch DOI: 10.1016/j.artint.2024.104244
   ✓ OK
→ [107] Fetch DOI: 10.1109/access.2022.3207765
   ✓ OK
→ [108] Fetch DOI: 10.1109/DSAA54385.2022.10032407
   ✓ OK
→ [109] Fetch DOI: 10.1140/epjds/s13688-022-00315-z
   ✓ OK
→ [110] Fetch DOI: 10.30682/ildia2101f
   ✓ OK
→ [111] Fetch DOI: 10.1007/978-3-030-10997-4_13
   ✓ OK
→ [112] Fetch DOI: 10.1007/978-3-030-43823-4_14
   ✓ OK
→ [113] Fetch DOI: 10.1007/978-3-030-46150-8_12
   ✓ OK
→ [114] Fetch DOI: 10.1609/aaai.v33i01.33019780
   ✓ OK
→ [115] Fetch DOI: 10.1109/MIS.2019.2957223
   ✓ OK
→ [116] Fetch DOI: 10.1145/3461702.3462553
   ✓ OK
→ [117] Fetch DOI: 10.3233/FAIA220209
   ✓ OK
→ [118] Fetch DOI: 10.1016/j.artint.2021.103457
   ✓ OK
→ [119] Fetch DOI: 10.3389/frai.2021.699448
   ✓ OK
→ [120] Fetch DOI: 10.1007/978-3-030-24409-5_9
   ✓ OK
⊘ [121] DOI mancante o non valido
→ [122] Fetch DOI: 10.1109/ISCC53001.2021.9631485
   ✓ OK
→ [123] Fetch DOI: 10.1007/978-3-030-61527-7_24
   ✓ OK
→ [124] Fetch DOI: 10.1007/978-3-030-88942-5_27
   ✓ OK
→ [125] Fetch DOI: 10.1016/j.ipm.2021.102657
   ✓ OK
→ [126] Fetch DOI: 10.1007/978-3-030-65965-3_34
   ✓ OK
→ [127] Fetch DOI: 10.1109/CogMI52975.2021.00014
   ✓ OK
→ [128] Fetch DOI: 10.1109/cogmi52975.2021.00016
   ✓ OK
→ [129] Fetch DOI: 10.1609/aaai.v34i09.7116
   ✓ OK
→ [130] Fetch DOI: 10.3390/e23081064
   ✓ OK
→ [131] Fetch DOI: 10.1007/978-3-030-76409-8
   ✓ OK
→ [132] Fetch DOI: 10.1016/j.artint.2020.103428
   ✓ OK
→ [133] Fetch DOI: 10.1007/978-3-030-61527-7_27
   ✓ OK
⊘ [134] DOI mancante o non valido
→ [135] Fetch DOI: 10.1145/3351095.3372855
   ✓ OK
⊘ [136] DOI mancante o non valido
→ [137] Fetch DOI: 10.1109/ICDM50108.2020.00122
   ✓ OK
→ [138] Fetch DOI: 10.1109/CogMI50398.2020.00029
   ✓ OK
⊘ [139] DOI mancante o non valido
→ [140] Fetch DOI: 1806.09936
   ✗ HTTP error (code 404) per DOI 1806.09936
     → DOI not found su Crossref.
→ [141] Fetch DOI: 1805.10820
   ✗ HTTP error (code 404) per DOI 1805.10820
     → DOI not found su Crossref.

============================================================
Recuperati 111 BibTeX su 141 papers totali
DOI falliti o mancanti: 30
Indici dei DOI falliti/mancanti: [5, 7, 8, 10, 11, 13, 14, 16, 25, 26, 35, 36, 37, 38, 41, 42, 43, 61, 81, 82, 83, 87, 91, 94, 120, 133, 135, 138, 139, 140]
============================================================

# Enrichment of BibTeX entries with CSV data
Arricchimento delle voci BibTeX con i dati presenti nel CSV.

In [17]:
import bibtexparser
from bibtexparser.bparser import BibTexParser
from bibtexparser.bibdatabase import BibDatabase
from bibtexparser.bwriter import BibTexWriter
import re

def enrich_bibtex_with_csv(bibs_list, papers_df, bib_indices):
    """
    Arricchisce le voci BibTeX con i dati del CSV secondo il mapping definito.
    
    Args:
        bibs_list: lista di stringhe BibTeX ottenute dai DOI
        papers_df: DataFrame pandas con i dati del CSV
        bib_indices: lista degli indici CSV corrispondenti a ciascun BibTeX
    
    Returns:
        lista di stringhe BibTeX arricchite
    """
    
    enriched_bibs = []
    
    for idx, bib_str in enumerate(bibs_list):
        # Crea un nuovo parser per ogni entry per evitare contaminazioni
        parser = BibTexParser(common_strings=True)
        
        # Parse il BibTeX
        bib_db = bibtexparser.loads(bib_str, parser=parser)
        
        if len(bib_db.entries) == 0:
            print(f"Avviso: entry {idx} non parsabile, skip")
            continue
            
        entry = bib_db.entries[0]
        
        # Trova la riga corrispondente nel CSV usando l'indice mappato
        csv_idx = bib_indices[idx]
        csv_row = papers_df.iloc[csv_idx]
        
        # 1. Cambia l'ID dell'entry con "Id di Riccardo"
        if pd.notna(csv_row.get('Id di Riccardo')):
            entry['ID'] = str(csv_row['Id di Riccardo'])
        
        # 2. Aggiungi/sovrascrivi abstract se presente nel CSV
        if pd.notna(csv_row.get('abstract')) and csv_row['abstract'].strip():
            entry['abstract'] = csv_row['abstract'].strip()
        
        # 3. Aggiungi Research line come campo "line" (non research_line!)
        # IMPORTANTE: il template usa entry.line, non entry.research_line
        # Il formato deve essere "1,3" senza parentesi graffe
        if pd.notna(csv_row.get('Research line')):
            rl_value = str(csv_row['Research line']).strip()
            # Rimuovi eventuali parentesi graffe
            rl_value = rl_value.strip('{}')
            # Usa il campo 'line' che è quello corretto per il template
            entry['line'] = rl_value
        
        # 4. Aggiungi visible on website
        if pd.notna(csv_row.get('visible on website')):
            entry['visible_on_website'] = str(csv_row['visible on website'])
        
        # 5. Aggiungi bibtex_show (sempre true se presente)
        entry['bibtex_show'] = 'true'
        
        # 6. Aggiungi selected se presente e uguale a TRUE nel CSV
        if pd.notna(csv_row.get('selected')):
            selected_value = str(csv_row['selected']).strip().upper()
            if selected_value == 'TRUE':
                entry['selected'] = 'true'
        
        # 7. Aggiungi Open access come campo custom
        if pd.notna(csv_row.get('Open access')):
            entry['open_access'] = str(csv_row['Open access'])
        
        # 8. Verifica e integra anno se mancante nel BibTeX
        if 'year' not in entry or not entry['year']:
            if pd.notna(csv_row.get('Year of publication')):
                entry['year'] = str(int(csv_row['Year of publication']))
        
        # 9. Aggiungi ISSN se presente nel CSV e non nel BibTeX
        if 'issn' not in entry or not entry['issn']:
            if pd.notna(csv_row.get('ISSN or eSSN')):
                entry['issn'] = str(csv_row['ISSN or eSSN'])
        
        # 10. Aggiungi pages se presente nel CSV e non nel BibTeX
        if 'pages' not in entry or not entry['pages']:
            if pd.notna(csv_row.get('Relevant pages')):
                entry['pages'] = str(csv_row['Relevant pages'])
        
        # 11. Aggiungi publisher se presente nel CSV e non nel BibTeX
        if 'publisher' not in entry or not entry['publisher']:
            if pd.notna(csv_row.get('Publisher')):
                entry['publisher'] = str(csv_row['Publisher'])
        
        # 12. Aggiungi address/location se presente nel CSV
        if pd.notna(csv_row.get('Place of publication')):
            if 'address' not in entry or not entry['address']:
                entry['address'] = str(csv_row['Place of publication'])
        
        # 13. Verifica e correggi il tipo di entry se necessario
        if pd.notna(csv_row.get('Type of scientific publication')):
            csv_type = csv_row['Type of scientific publication'].lower().strip()
            # Mappa i tipi comuni
            type_mapping = {
                'journal article': 'article',
                'conference paper': 'inproceedings',
                'book chapter': 'inbook',
                'preprint': 'misc'
            }
            if csv_type in type_mapping:
                entry['ENTRYTYPE'] = type_mapping[csv_type]
                
        # 14. Rinomina url in html e aggiungi DOI link
        # Prima rimuovi il campo url se presente e spostalo in html
        if 'url' in entry:
            entry['html'] = entry.pop('url')
        # Aggiungi html se non presente ma c'è doi link nel CSV
        if 'html' not in entry or not entry['html']:
            if pd.notna(csv_row.get('doi link')):
                entry['html'] = str(csv_row['doi link'])
                entry['url'] = str(csv_row['doi link'])
        
        # 15. Assicurati che il DOI sia presente
        if 'doi' not in entry or not entry['doi']:
            if pd.notna(csv_row.get('DOI')):
                entry['doi'] = str(csv_row['DOI'])
        
        # 16. Verifica title
        if 'title' not in entry or not entry['title']:
            if pd.notna(csv_row.get('Title of the scientific publication')):
                entry['title'] = str(csv_row['Title of the scientific publication'])
        
        # 17. Verifica authors - usa quelli del BibTeX se presenti, altrimenti CSV
        if 'author' not in entry or not entry['author']:
            if pd.notna(csv_row.get('Authors')):
                entry['author'] = str(csv_row['Authors'])
        
        # Ricostruisci il BibTeX arricchito
        db_enriched = BibDatabase()
        db_enriched.entries = [entry]
        
        writer = BibTexWriter()
        writer.indent = '  '
        writer.order_entries_by = None
        
        enriched_bib_str = bibtexparser.dumps(db_enriched, writer)
        enriched_bibs.append(enriched_bib_str)
        
        print(f"✓ Entry {idx+1}/{len(bibs_list)} arricchita: {entry.get('ID', 'no-id')}")
    
    return enriched_bibs

# Esegui l'arricchimento
print("Inizio arricchimento delle voci BibTeX...")
print(f"Numero di indici mappati: {len(bib_indices)}")
print("-" * 60)

enriched_bibs = enrich_bibtex_with_csv(bibs, papers, bib_indices)

print("-" * 60)
print(f"✓ Arricchimento completato! {len(enriched_bibs)} voci processate.")

print("\nEsempio della prima voce arricchita:")
print(enriched_bibs[0] if enriched_bibs else "Nessuna voce disponibile")

Inizio arricchimento delle voci BibTeX...
Numero di indici mappati: 111
------------------------------------------------------------
✓ Entry 1/111 arricchita: CBR2025
✓ Entry 2/111 arricchita: MBG2025
✓ Entry 3/111 arricchita: CMM2025
✓ Entry 4/111 arricchita: CMZ2025
✓ Entry 5/111 arricchita: BCN2025
✓ Entry 6/111 arricchita: AR2025
✓ Entry 7/111 arricchita: LCM2025c
✓ Entry 8/111 arricchita: PPF2025
✓ Entry 9/111 arricchita: PSW2025
✓ Entry 10/111 arricchita: CBG2025
✓ Entry 11/111 arricchita: RMM2025
✓ Entry 12/111 arricchita: LCM2025
✓ Entry 13/111 arricchita: MDP2025
✓ Entry 14/111 arricchita: MPG2025
✓ Entry 15/111 arricchita: FGB2025
✓ Entry 16/111 arricchita: CBS2025
✓ Entry 17/111 arricchita: SGP2025
✓ Entry 18/111 arricchita: TDP2025
✓ Entry 19/111 arricchita: SBB2025
✓ Entry 20/111 arricchita: FCG2025
✓ Entry 21/111 arricchita: CPG2025
✓ Entry 22/111 arricchita: SCG2024
✓ Entry 23/111 arricchita: FPT2024
✓ Entry 24/111 arricchita: SGM2024
✓ Entry 25/111 arricchita: ZPR2024
✓ Entry 26/111 arricchita: LG2024
✓ Entry 27/111 arricchita: PKP2024
✓ Entry 28/111 arricchita: SMM2024
✓ Entry 29/111 arricchita: PPS2024
✓ Entry 30/111 arricchita: FGG2024
✓ Entry 31/111 arricchita: TLT2024
✓ Entry 32/111 arricchita: P2024
✓ Entry 33/111 arricchita: CBM2024
✓ Entry 34/111 arricchita: SCM2024
✓ Entry 35/111 arricchita: LBC2024
✓ Entry 36/111 arricchita: MBP2024b
✓ Entry 37/111 arricchita: CSG2024b
✓ Entry 38/111 arricchita: CSG2024
✓ Entry 39/111 arricchita: MBG2024
✓ Entry 40/111 arricchita: MSG2024
✓ Entry 41/111 arricchita: NMB2024
✓ Entry 42/111 arricchita: CG2024
✓ Entry 43/111 arricchita: DPG2024
✓ Entry 44/111 arricchita: MBP2024
✓ Entry 45/111 arricchita: SGC2024
✓ Entry 46/111 arricchita: FGP2024
✓ Entry 47/111 arricchita: GMS2024
✓ Entry 48/111 arricchita: HNS2024
✓ Entry 49/111 arricchita: PBG2024
✓ Entry 50/111 arricchita: BGG2023
✓ Entry 51/111 arricchita: CNP2023
✓ Entry 52/111 arricchita: MBG2023
✓ Entry 53/111 arricchita: PMG2023
✓ Entry 54/111 arricchita: GLB2023
✓ Entry 55/111 arricchita: PSG2023
✓ Entry 56/111 arricchita: SRT2023
✓ Entry 57/111 arricchita: SGM2023
✓ Entry 58/111 arricchita: SRT2023b
✓ Entry 59/111 arricchita: NPR2023
✓ Entry 60/111 arricchita: PFP2023
✓ Entry 61/111 arricchita: BC2023
✓ Entry 62/111 arricchita: MM2023
✓ Entry 63/111 arricchita: CFR2023
✓ Entry 64/111 arricchita: DGS2023
✓ Entry 65/111 arricchita: PBF2023
✓ Entry 66/111 arricchita: CGG2023
✓ Entry 67/111 arricchita: LSG2023
✓ Entry 68/111 arricchita: NMG2022
✓ Entry 69/111 arricchita: PBP2022
✓ Entry 70/111 arricchita: AAB2022
✓ Entry 71/111 arricchita: G2022
✓ Entry 72/111 arricchita: BGG2023c
✓ Entry 73/111 arricchita: FGP2022
✓ Entry 74/111 arricchita: NMG2022b
✓ Entry 75/111 arricchita: SGN2022
✓ Entry 76/111 arricchita: SMM2022
✓ Entry 77/111 arricchita: NPR2022
✓ Entry 78/111 arricchita: CDF2021
✓ Entry 79/111 arricchita: GMR2018
✓ Entry 80/111 arricchita: MG2022
✓ Entry 81/111 arricchita: GMR2022
✓ Entry 82/111 arricchita: Pedreschi_2025
✓ Entry 83/111 arricchita: TSS2022
✓ Entry 84/111 arricchita: BGG2023b
✓ Entry 85/111 arricchita: VMG2022
✓ Entry 86/111 arricchita: PB2021
✓ Entry 87/111 arricchita: GSN2021
✓ Entry 88/111 arricchita: SGM2019
✓ Entry 89/111 arricchita: GMM2019
✓ Entry 90/111 arricchita: PGG2019
✓ Entry 91/111 arricchita: GMG2019
✓ Entry 92/111 arricchita: GM2021
✓ Entry 93/111 arricchita: MGY2021b
✓ Entry 94/111 arricchita: SGM2021
✓ Entry 95/111 arricchita: GD2021
✓ Entry 96/111 arricchita: PGM2019
✓ Entry 97/111 arricchita: MGY2021
✓ Entry 98/111 arricchita: LGR2020
✓ Entry 99/111 arricchita: BGM2021
✓ Entry 100/111 arricchita: PPB2021
✓ Entry 101/111 arricchita: NPN2020
✓ Entry 102/111 arricchita: MG2021
✓ Entry 103/111 arricchita: CGG2021
✓ Entry 104/111 arricchita: GMM2020
✓ Entry 105/111 arricchita: RAB2021
✓ Entry 106/111 arricchita: GMP2021
✓ Entry 107/111 arricchita: G2021
✓ Entry 108/111 arricchita: NPM2020
✓ Entry 109/111 arricchita: PPP2020
✓ Entry 110/111 arricchita: GM2020
✓ Entry 111/111 arricchita: GMS2020
------------------------------------------------------------
✓ Arricchimento completato! 111 voci processate.

Esempio della prima voce arricchita:
@article{CBR2025,
  abstract = {In this paper, we focus on estimating the causal effect of an intervention over time on a dynamical system.
To that end, we formally define causal interventions and their effects over time on discrete-time stochastic processes (DSPs).
Then, we show under which conditions the equilibrium states of a DSP, both before and after a causal intervention, can be captured by a structural causal model (SCM).
With such an equivalence at hand, we provide an explicit mapping from vector autoregressive models (VARs), broadly applied in econometrics, to linear, but potentially cyclic and/or affected by unmeasured confounders, SCMs. The resulting causal VAR framework allows us to perform causal inference over time from observational time series data.
Our experiments on synthetic and real-world datasets show that the proposed framework achieves strong performance in terms of observational forecasting while enabling accurate estimation of the causal effect of interventions on dynamical systems.
We demonstrate, through a case study, the potential practical questions that can be addressed using the proposed causal VAR framework.},
  author = {Cinquini, Martina and Beretta, Isacco and Ruggieri, Salvatore and Valera, Isabel},
  bibtex_show = {true},
  doi = {10.1609/aaai.v39i14.33626},
  html = {http://dx.doi.org/10.1609/aaai.v39i14.33626},
  issn = {2159-5399},
  journal = {Proceedings of the AAAI Conference on Artificial Intelligence},
  line = {2},
  month = {April},
  number = {14},
  open_access = {Gold},
  pages = {14832–14839},
  publisher = {Association for the Advancement of Artificial Intelligence (AAAI)},
  selected = {true},
  title = {A Practical Approach to Causal Inference over Time},
  visible_on_website = {YES},
  volume = {39},
  year = {2025}
}

# From CSV to Bibtex (senza usare DOI)

## Caricamento Dati

In [18]:
# crea un df missing_doi utilizzando la lista dei failed_doi_indices
missing_doi_rows = papers.iloc[failed_doi_indices]
missing_doi_rows

,Id in EU,id,Id di Riccardo,In zotero,EU selection,Title of the scientific publication,abstract,doi link,DOI,Year of publication,...,Publisher,Authors,ISSN or eSSN,Title of the journal or equivalent,"Number, date",Place of publication,Relevant pages,Joint Public / Private publication,Peer-review,Research line
5,NaN,131,PMG2025,True,False,Deferring Concept Bottleneck Models: Learning ...,NaN,NaN,NaN,2025,...,NaN,"Andrea Pugnana, Riccardo Massidda, Francesco G...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,2"
7,NaN,146,JCD2025,NaN,False,DeepProofLog: Efficient Proving in Deep Stocha...,NaN,NaN,NaN,2025,...,NaN,"Ying Jiao, Rodrigo Castellano Ontiveros, Luc D...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
8,NaN,147,PPK2025,NaN,False,Disentangled and Self-Explainable Node Represe...,NaN,https://doi.org/10.48550/arXiv.2410.21043,10.48550/arXiv.2410.21043,2025,...,NaN,"Simone Piaggesi, André Panisson, Megha Khosla",NaN,Transactions on Machine Learning Research,NaN,NaN,NaN,NaN,NaN,1
10,NaN,126,HCC2025,True,NaN,FeDa4Fair: Client-Level Federated Datasets for...,Federated Learning (FL) enables collaborative ...,NaN,NaN,2025,...,NaN,"Xenia Heilmann, Luca Corbucci, Mattia Cerrato,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
11,NaN,163,BLF2025,NaN,False,A Simulation Framework for Studying Systemic E...,Recommender systems continuously interact with...,https://doi.org/10.48550/arXiv.2510.14857,10.48550/arXiv.2510.14857,2025,...,NaN,"G. Barlacchi, M. Lalli, E. Ferragina, F. Giann...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
13,NaN,145,LCM2025b,NaN,False,A Note on Methods for Explainable Malware Anal...,NaN,NaN,NaN,2025,...,NaN,"Cristiano Landi, Alessio Cascione, Marta March...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
14,NaN,120,SFF2025,True,False,"MAINLE: a Multi-Agent, Interactive, Natural La...",NaN,NaN,NaN,2025,...,NaN,"Paulo Bruno Serafim, Romula Ferrer Filho, STEN...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,3"
16,120.0,148,PGG2025,NaN,False,Explanations Go Linear: Post-hoc Explainabilit...,NaN,ancora non disponibile,NaN,2025,...,NaN,"Simone Piaggesi, Riccardo Guidotti, Fosca Gian...",NaN,2025 IEEE International Conference on Data Mining,NaN,NaN,NaN,NaN,NaN,1
25,117.0,163,NMG2025,True,True,Evaluating the Privacy Exposure of Interpretab...,"During the last few years, the abundance of da...",http://www.tdp.cat,NaN,2025,...,"Trans. Data Priv. 18 (2), 67-93","Francesca Naretto, Anna Monreale, Fosca Giannotti",NaN,Evaluating the Privacy Exposure of Interpretab...,NaN,NaN,NaN,NaN,NaN,"1,5"
26,NaN,119,GGG2025,True,False,"""Learning by surprise"": a new characterization...",NaN,NaN,NaN,2025,...,NaN,"Daniele Gambetta, Gizem Gezici, Fosca Giannott...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
35,119.0,142,MBG2024bb,True,True,Multi-Perspective Stance Detection,Subjective NLP tasks usually rely on human ann...,https://ceur-ws.org/Vol-3825/short6-4.pdf,NaN,2024,...,NaN,"Benedetta Muscato, Praveen Bushipaka, Gizem Ge...",NaN,CEUR,2024,"Aachen, Germany",NaN,NaN,NaN,"4,5"
36,118.0,134,CMP2024,True,True,Beyond Headlines: A Corpus of Femicides News C...,How newspapers cover news significantly impact...,https://aclanthology.org/2024.clicit-1.21/,NaN,2024,...,NaN,"Eleonora Cappuccio, Benedetta Muscato, Laura P...",NaN,CEUR,2024,"Aachen, Germany",NaN,NaN,NaN,"4,5"
37,NaN,133,PFC2024,True,False,A survey on the impact of AI-based recommender...,Recommendation systems and assistants (in shor...,https://doi.org/10.48550/arXiv.2407.01630,10.48550/arXiv.2407.01630,2024,...,arXiv,"Luca Pappalardo, Emanuele Ferragina, Salvatore...",NaN,NaN,2025-02-20,NaN,NaN,NaN,NaN,"3,4,5"
38,107.0,149,BEF2024,True,True,Requirements of eXplainable AI in Algorithmic ...,AI models for ranking candidates to a job posi...,https://ceur-ws.org/Vol-3744/paper8.pdf,NaN,2024,...,NaN,"A. Beretta, G. Ercoli, A. Ferraro, R. Guidotti...",NaN,"AIMMES 2024: AI bias – Measurements, Mitigatio...",NaN,NaN,NaN,NaN,NaN,1
41,45.0,64,GMO2024,True,True,The ethical impact assessment of selling life ...,The Artificial Intelligence Act (AIA) is a uni...,NaN,NaN,2024,...,NaN,"Gezici, Gizem; Mannari, Chiara; Orlandi, Lorenzo",NaN,HHAI-WS 2023 - Workshops at the Second Interna...,20,NaN,NaN,no,No,5
42,88.0,107,GMB2024,True,True,XAI in healthcare,The evolution of Explainable Artificial Intell...,https://ceur-ws.org/Vol-3825/short2-1.pdf,NaN,2024,...,NaN,Gezici G.; Metta C; Beretta A.; Pellungrini R....,NaN,xAI 2024 - 2nd World Conference on eXplainable...,1,NaN,NaN,NaN,Yes,"4,5"
43,87.0,106,MMM2024,True,True,An Overview of Recent Approaches to Enable Div...,The varied backgrounds and experiences of huma...,https://aclanthology.org/2024.nlperspectives-1.5/,NaN,2024,...,ELRA and ICCL,"Benedetta Muscato, Chandana Sree Mala, Marta M...",NaN,Proceedings of the 3rd Workshop on Perspectivi...,2024-10-31,"Torino, Italia",49--55,NaN,NaN,3
61,68.0,87,LPP2024,True,False,Interpretable and Fair Mechanisms for Abstaini...,Abstaining classifiers have the option to refr...,10.1007/978-3-031-70368-3_25,"[75,46,72,75,50,73,78].",2024,...,NaN,"Daphne Lenders, Andrea Pugnana, Roberto Pellun...",NaN,"Lecture Notes in Computer Science, Machine Lea...",NaN,NaN,NaN,no,Yes,"1,5"
81,36.0,55,PR2023,True,True,AUC-based Selective Classification,Selective classification (or classification wi...,https://proceedings.mlr.press/v206/pugnana23a....,NaN,2023,...,NaN,"Pugnana Andrea, Ruggieri Salvatore",NaN,Proceedings of The 26th International Conferen...,NaN,NaN,2494--2514,NaN,NaN,2
82,89.0,108,RCO2023,True,True,Position Paper: On the Role of Abductive Reaso...,This position paper provides insights aiming a...,NaN,NaN,2023,...,NaN,Andrea Rafanelli; Stefania Costantini; Andrea ...,NaN,NaN,1,NaN,NaN,NaN,Yes,2
83,97.0,116,F2023,True,True,Explain and interpret few-shot learning,Recent advancements in Artificial Intelligence...,https://ceur-ws.org/Vol-3554/paper38.pdf,NaN,2023,...,NaN,Fedele A.,NaN,xAI-2023 - 1st World Conference on eXplainable...,NaN,NaN,NaN,NaN,No,1
87,NaN,51,LCM2023,True,False,Modeling Events and Interactions through Tempo...,"In real-world scenario, many phenomena produce...",https://doi.org/10.48550/arxiv.2303.06067,10.48550/ARXIV.2303.06067,2023,...,Arxiv,"Liguori Angelica, Caroprese Luciano, Minici Ma...",NaN,NaN,10 mar 2023,NaN,NaN,NaN,NaN,1
91,91.0,110,BRF2022,True,True,Explaining Black Box with Visual Exploration o...,Autoencoders are a powerful yet opaque feature...,https://doi.org/10.2312/evs.20221098,10.2312/evs.20221098,2022,...,NaN,"Bodria, Francesco; Rinzivillo, Salvatore; Fadd...",NaN,NaN,10,NaN,NaN,NaN,Yes,"1,3"
94,96.0,115,BCM2022,True,True,User-driven counterfactual generator: a human ...,"In this paper, we critically examine the limit...",https://ceur-ws.org/Vol-3554/paper15.pdf,NaN,2022,...,NaN,Beretta I; Cappuccio E; Marchiori Manerba M,NaN,xAI-2023 - 1st World Conference on eXplainable...,1,NaN,NaN,NaN,Yes,"1,3"
120,27.0,28,GR2021,NaN,False,Ensemble of Counterfactual Explainers,"In eXplainable Artificial Intelligence (XAI), ...",https://pages.di.unipi.it/ruggieri/Papers/ds20...,NaN,2021,...,NaN,"Guidotti Riccardo, Ruggieri Salvatore",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
133,NaN,4,M2020,NaN,False,Rischi etico-legali dell’Intelligenza Artificiale,"Nowadays, a wide variety of personal data, des...",https://www.dpceonline.it/index.php/dpceonline...,NaN,2020,...,NaN,Monreale Anna,2037-6677,"DPCE Online, [S.l.], v. 44, n. 3, oct. 2020. I...",2020,NaN,NaN,NaN,NaN,5
135,10.0,7,RGG2020,NaN,False,Opening the black box: a primer for anti-discr...,The pervasive adoption of Artificial Intellige...,https://hdl.handle.net/11568/1088440,NaN,2020,...,NaN,"Ruggieri Salvatore, Giannotti Fosca, Guidotti ...",NaN,ANNUARIO DI DIRITTO COMPARATO E DI STUDI LEGIS...,NaN,Italy,NaN,NaN,NaN,1
138,NaN,3,GMP2019,NaN,False,The AI black box explanation problem,The use of machine learning in decision-making...,https://ercim-news.ercim.eu/images/stories/EN1...,NaN,2019,...,ERCIM – the European Research Consortium for I...,"Guidotti Riccardo, Monreale Anna, Pedreschi Dino",NaN,"ERCIM News, 116, 12-13",2019,NaN,NaN,NaN,NaN,"1,2,3"
139,NaN,2,PGG2018,NaN,False,Open the Black Box Data-Driven Explanation of ...,Black box systems for automated decision makin...,https://arxiv.org/abs/1806.09936,1806.09936,2018,...,Arxive,"Pedreschi Dino, Giannotti Fosca, Guidotti Ricc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
140,NaN,1,GMR2018a,NaN,False,Local Rule-Based Explanations of Black Box Dec...,The recent years have witnessed the rise of ac...,https://arxiv.org/abs/1805.10820,1805.10820,2018,...,Arxive,"Guidotti Riccardo, Monreale Anna, Ruggieri Sal...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

## Crea i Bibtex dei lavori senza DOI

In [19]:
import bibtexparser
from bibtexparser.bibdatabase import BibDatabase
from bibtexparser.bwriter import BibTexWriter
import re

def create_bibtex_with_csv_only(papers_df):
    """
    Crea voci BibTeX complete a partire solo dai dati del CSV, senza utilizzare il DOI.
    Il formato è compatibile con il template Jekyll che usa il campo 'line' per research line.
    
    Args:
        papers_df: DataFrame pandas con i dati del CSV
    
    Returns:
        lista di stringhe BibTeX create dai dati CSV
    """
    
    bibtex_entries = []
    
    # Mappa dei tipi di pubblicazione CSV -> BibTeX entry type
    type_mapping = {
        'journal article': 'article',
        'conference paper': 'inproceedings',
        'book chapter': 'inbook',
        'preprint': 'misc',
        'book': 'book',
        'proceedings': 'proceedings'
    }
    
    for idx, row in papers_df.iterrows():
        # Salta le righe che hanno già un DOI valido (sono già state processate)
        #if pd.notna(row.get('DOI')) and row['DOI'].strip():
        #    continue
            
        # Crea un dizionario per l'entry BibTeX
        entry = {}
        
        # 1. Determina il tipo di entry
        csv_type = str(row.get('Type of scientific publication', 'misc')).lower().strip()
        entry['ENTRYTYPE'] = type_mapping.get(csv_type, 'misc')
        
        # 2. Genera l'ID dell'entry (usa "Id di Riccardo" se presente, altrimenti genera)
        if pd.notna(row.get('Id di Riccardo')):
            entry['ID'] = str(row['Id di Riccardo'])
        else:
            # Genera un ID simile al formato esistente
            authors = str(row.get('Authors', 'Unknown'))
            first_author = authors.split(',')[0].strip().replace(' ', '_').replace('.', '')
            year = str(int(row['Year of publication'])) if pd.notna(row.get('Year of publication')) else 'nodate'
            title_words = str(row.get('Title of the scientific publication', '')).split()[:2]
            title_part = '_'.join([w.strip('.,;:!?') for w in title_words]).lower()
            entry['ID'] = f"{first_author}_{year}_{title_part}"
        
        # ORDINE DEI CAMPI come nell'esempio: abstract, author, bibtex_show, altri campi, line, month, title, year
        
        # Abstract (primo campo nell'esempio)
        if pd.notna(row.get('abstract')) and row['abstract'].strip():
            entry['abstract'] = str(row['abstract']).strip()
        
        # Authors (formato con "and" se necessario)
        if pd.notna(row.get('Authors')):
            authors_str = str(row['Authors'])
            # Converte virgole in "and" per formato BibTeX standard
            entry['author'] = authors_str.replace(',', ' and')
        else:
            entry['author'] = 'Unknown'
        
        # bibtex_show
        entry['bibtex_show'] = 'true'
        
        # selected (se presente e uguale a TRUE)
        if pd.notna(row.get('selected')):
            selected_value = str(row['selected']).strip().upper()
            if selected_value == 'TRUE':
                entry['selected'] = 'true'
        
        # DOI (se presente)
        if pd.notna(row.get('DOI')):
            entry['doi'] = str(row['DOI'])
        
        # HTML link
        if pd.notna(row.get('doi link')):
            entry['html'] = str(row['doi link'])
        
        # Journal/Booktitle (dipende dal tipo)
        if entry['ENTRYTYPE'] == 'article':
            if pd.notna(row.get('Title of the journal or equivalent')):
                entry['journal'] = str(row['Title of the journal or equivalent']).strip()
        elif entry['ENTRYTYPE'] in ['inproceedings', 'inbook']:
            if pd.notna(row.get('Title of the journal or equivalent')):
                entry['booktitle'] = str(row['Title of the journal or equivalent']).strip()
        
        # ISSN
        if pd.notna(row.get('ISSN or eSSN')):
            entry['issn'] = str(row['ISSN or eSSN'])
        
        # Research line - CAMPO "line" con formato {3,5}
        # Il writer aggiunge automaticamente le graffe, quindi metto solo il valore
        if pd.notna(row.get('Research line')):
            rl_value = str(row['Research line']).strip()
            # Rimuovi eventuali parentesi graffe se presenti
            rl_value = rl_value.strip('{}')
            # Non aggiungere graffe, il writer le metterà automaticamente
            entry['line'] = rl_value
        
        # Month (0 se non specificato, come nell'esempio)
        if pd.notna(row.get('Month')):
            entry['month'] = str(row['Month'])
        else:
            entry['month'] = '0'
        
        # Pages
        if pd.notna(row.get('Relevant pages')):
            entry['pages'] = str(row['Relevant pages'])
        
        # Publisher
        if pd.notna(row.get('Publisher')):
            entry['publisher'] = str(row['Publisher'])
        
        # Address/Location
        if pd.notna(row.get('Place of publication')):
            entry['address'] = str(row['Place of publication'])
        
        # Title (obbligatorio)
        if pd.notna(row.get('Title of the scientific publication')):
            entry['title'] = str(row['Title of the scientific publication']).strip()
        else:
            entry['title'] = 'Untitled'
        
        # Volume (se presente)
        if pd.notna(row.get('Volume')):
            entry['volume'] = str(row['Volume'])
        
        # Year (obbligatorio, ultimo campo nell'esempio)
        if pd.notna(row.get('Year of publication')):
            entry['year'] = str(int(row['Year of publication']))
        else:
            entry['year'] = ''
        
        # PDF (se presente)
        if pd.notna(row.get('PDF filename')):
            entry['pdf'] = str(row['PDF filename'])
        
        # Crea il database BibTeX
        db = BibDatabase()
        db.entries = [entry]
        
        # Scrivi il BibTeX
        writer = BibTexWriter()
        writer.indent = '    '  # 4 spazi come nell'esempio
        writer.order_entries_by = None
        writer.add_trailing_comma = True
        
        bibtex_str = bibtexparser.dumps(db, writer)
        bibtex_entries.append(bibtex_str)
        
        print(f"✓ Entry {idx+1} creata: {entry.get('ID', 'no-id')}")
    
    return bibtex_entries

# Test della funzione con i paper senza DOI
print("Creazione voci BibTeX per paper senza DOI...")
print(f"Numero di paper senza DOI: {len(missing_doi_rows)}")
print("-" * 60)

bibtex_no_doi = create_bibtex_with_csv_only(missing_doi_rows)

print("-" * 60)
print(f"✓ Creazione completata! {len(bibtex_no_doi)} voci create.")

if bibtex_no_doi:
    print("\nEsempio della prima voce creata:")
    print(bibtex_no_doi[0])

Creazione voci BibTeX per paper senza DOI...
Numero di paper senza DOI: 30
------------------------------------------------------------
✓ Entry 6 creata: PMG2025
✓ Entry 8 creata: JCD2025
✓ Entry 9 creata: PPK2025
✓ Entry 11 creata: HCC2025
✓ Entry 12 creata: BLF2025
✓ Entry 14 creata: LCM2025b
✓ Entry 15 creata: SFF2025
✓ Entry 17 creata: PGG2025
✓ Entry 26 creata: NMG2025
✓ Entry 27 creata: GGG2025
✓ Entry 36 creata: MBG2024bb
✓ Entry 37 creata: CMP2024
✓ Entry 38 creata: PFC2024
✓ Entry 39 creata: BEF2024
✓ Entry 42 creata: GMO2024
✓ Entry 43 creata: GMB2024
✓ Entry 44 creata: MMM2024
✓ Entry 62 creata: LPP2024
✓ Entry 82 creata: PR2023
✓ Entry 83 creata: RCO2023
✓ Entry 84 creata: F2023
✓ Entry 88 creata: LCM2023
✓ Entry 92 creata: BRF2022
✓ Entry 95 creata: BCM2022
✓ Entry 121 creata: GR2021
✓ Entry 134 creata: M2020
✓ Entry 136 creata: RGG2020
✓ Entry 139 creata: GMP2019
✓ Entry 140 creata: PGG2018
✓ Entry 141 creata: GMR2018a
------------------------------------------------------------
✓ Creazione completata! 30 voci create.

Esempio della prima voce creata:
@misc{PMG2025,
    author = {Andrea Pugnana and Riccardo Massidda and Francesco Giannini and Pietro Barbiero and Mateo Espinosa Zarlenga and Roberto Pellungrini and Gabriele Dominici and Fosca Giannotti and Davide Bacciu},
    bibtex_show = {true},
    line = {1,2},
    month = {0},
    title = {Deferring Concept Bottleneck Models: Learning to Defer Interventions to Inaccurate Experts},
    year = {2025},
}

# test di salvatagguio di un bibtex solo per quelli senza doi

# Salva tutte le voci BibTeX nel file
output_file = "xai_papers.bib"

with open(output_file, "w", encoding='utf-8') as file:
    for item in bibtex_no_doi:
        file.write(item + "\n")

print(f"✓ File '{output_file}' salvato con successo!")
print(f"  Totale voci create da CSV: {len(bibtex_no_doi)}")
print(f"  TOTALE voci: {len(bibtex_no_doi)}")

In [20]:
# Combina i BibTeX da DOI e quelli creati solo da CSV
all_bibtex = enriched_bibs + bibtex_no_doi

# Salva tutte le voci BibTeX nel file
output_file = "xai_papers.bib"

with open(output_file, "w", encoding='utf-8') as file:
    for item in all_bibtex:
        file.write(item + "\n")

print(f"✓ File '{output_file}' salvato con successo!")
print(f"  Totale voci da DOI: {len(enriched_bibs)}")
print(f"  Totale voci create da CSV: {len(bibtex_no_doi)}")
print(f"  TOTALE voci: {len(all_bibtex)}")

✓ File 'xai_papers.bib' salvato con successo!
  Totale voci da DOI: 111
  Totale voci create da CSV: 30
  TOTALE voci: 141